/* This file was automatically generated by CasADi 3.6.4.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) ship_constr_h_fun_jac_uxt_zt_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[11] = {7, 1, 0, 7, 0, 1, 2, 3, 4, 5, 6};
static const casadi_int casadi_s1[6] = {2, 1, 0, 2, 0, 1};
static const casadi_int casadi_s2[3] = {0, 0, 0};
static const casadi_int casadi_s3[29] = {25, 1, 0, 25, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24};
static const casadi_int casadi_s4[9] = {5, 1, 0, 5, 0, 1, 2, 3, 4};
static const casadi_int casadi_s5[43] = {9, 5, 0, 7, 14, 21, 28, 35, 2, 3, 4, 5, 6, 7, 8, 2, 3, 4, 5, 6, 7, 8, 2, 3, 4, 5, 6, 7, 8, 2, 3, 4, 5, 6, 7, 8, 2, 3, 4, 5, 6, 7, 8};
static const casadi_int casadi_s6[3] = {5, 0, 0};

/* ship_constr_h_fun_jac_uxt_zt:(i0[7],i1[2],i2[],i3[25])->(o0[5],o1[9x5,35nz],o2[5x0]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a10, a100, a101, a102, a103, a104, a105, a106, a107, a108, a109, a11, a110, a111, a112, a113, a114, a115, a116, a117, a118, a119, a12, a120, a121, a122, a123, a124, a125, a126, a127, a128, a129, a13, a130, a131, a132, a133, a134, a135, a136, a137, a138, a139, a14, a140, a141, a142, a143, a144, a145, a146, a147, a148, a149, a15, a150, a151, a152, a153, a154, a16, a17, a18, a19, a2, a20, a21, a22, a23, a24, a25, a26, a27, a28, a29, a3, a30, a31, a32, a33, a34, a35, a36, a37, a38, a39, a4, a40, a41, a42, a43, a44, a45, a46, a47, a48, a49, a5, a50, a51, a52, a53, a54, a55, a56, a57, a58, a59, a6, a60, a61, a62, a63, a64, a65, a66, a67, a68, a69, a7, a70, a71, a72, a73, a74, a75, a76, a77, a78, a79, a8, a80, a81, a82, a83, a84, a85, a86, a87, a88, a89, a9, a90, a91, a92, a93, a94, a95, a96, a97, a98, a99;
  a0=arg[0]? arg[0][0] : 0;
  a1=2.0000000000000001e-01;
  a2=arg[0]? arg[0][3] : 0;
  a3=arg[0]? arg[0][2] : 0;
  a4=cos(a3);
  a5=(a2*a4);
  a5=(a1*a5);
  a5=(a0+a5);
  a6=arg[3]? arg[3][0] : 0;
  a7=arg[3]? arg[3][3] : 0;
  a7=(a1*a7);
  a7=(a6+a7);
  a8=(a5-a7);
  a9=arg[0]? arg[0][5] : 0;
  a10=arg[0]? arg[0][6] : 0;
  a9=(a9+a10);
  a10=10.;
  a11=1.6899999999999999e+01;
  a12=casadi_sq(a2);
  a13=1.0000000000000001e-05;
  a12=(a12+a13);
  a12=sqrt(a12);
  a13=(a11*a12);
  a10=(a10+a13);
  a13=(a10*a2);
  a9=(a9-a13);
  a13=36.;
  a9=(a9/a13);
  a9=(a1*a9);
  a9=(a2+a9);
  a13=(a8*a9);
  a14=arg[0]? arg[0][4] : 0;
  a14=(a1*a14);
  a14=(a3+a14);
  a15=cos(a14);
  a16=(a13*a15);
  a17=arg[0]? arg[0][1] : 0;
  a18=sin(a3);
  a19=(a2*a18);
  a19=(a1*a19);
  a19=(a17+a19);
  a20=arg[3]? arg[3][1] : 0;
  a21=arg[3]? arg[3][4] : 0;
  a21=(a1*a21);
  a21=(a20+a21);
  a22=(a19-a21);
  a23=(a22*a9);
  a24=sin(a14);
  a25=(a23*a24);
  a16=(a16+a25);
  a25=(a5-a7);
  a26=casadi_sq(a25);
  a27=(a19-a21);
  a28=casadi_sq(a27);
  a26=(a26+a28);
  a26=sqrt(a26);
  a16=(a16/a26);
  a7=(a5-a7);
  a28=casadi_sq(a7);
  a21=(a19-a21);
  a29=casadi_sq(a21);
  a28=(a28+a29);
  a28=sqrt(a28);
  a29=arg[3]? arg[3][2] : 0;
  a30=(a28-a29);
  a31=1.0000000000000000e-04;
  a32=(a29+a31);
  a30=(a30/a32);
  a30=(a16+a30);
  a33=9.7999999999999998e-01;
  a34=(a0-a6);
  a35=(a34*a2);
  a36=cos(a3);
  a37=(a35*a36);
  a38=(a17-a20);
  a39=(a38*a2);
  a40=sin(a3);
  a41=(a39*a40);
  a37=(a37+a41);
  a41=(a0-a6);
  a42=casadi_sq(a41);
  a43=(a17-a20);
  a44=casadi_sq(a43);
  a42=(a42+a44);
  a42=sqrt(a42);
  a37=(a37/a42);
  a6=(a0-a6);
  a44=casadi_sq(a6);
  a20=(a17-a20);
  a45=casadi_sq(a20);
  a44=(a44+a45);
  a44=sqrt(a44);
  a45=(a44-a29);
  a29=(a29+a31);
  a45=(a45/a29);
  a45=(a37+a45);
  a45=(a33*a45);
  a30=(a30-a45);
  if (res[0]!=0) res[0][0]=a30;
  a30=arg[3]? arg[3][5] : 0;
  a45=arg[3]? arg[3][8] : 0;
  a45=(a1*a45);
  a45=(a30+a45);
  a46=(a5-a45);
  a47=(a46*a9);
  a48=cos(a14);
  a49=(a47*a48);
  a50=arg[3]? arg[3][6] : 0;
  a51=arg[3]? arg[3][9] : 0;
  a51=(a1*a51);
  a51=(a50+a51);
  a52=(a19-a51);
  a53=(a52*a9);
  a54=sin(a14);
  a55=(a53*a54);
  a49=(a49+a55);
  a55=(a5-a45);
  a56=casadi_sq(a55);
  a57=(a19-a51);
  a58=casadi_sq(a57);
  a56=(a56+a58);
  a56=sqrt(a56);
  a49=(a49/a56);
  a45=(a5-a45);
  a58=casadi_sq(a45);
  a51=(a19-a51);
  a59=casadi_sq(a51);
  a58=(a58+a59);
  a58=sqrt(a58);
  a59=arg[3]? arg[3][7] : 0;
  a60=(a58-a59);
  a61=(a59+a31);
  a60=(a60/a61);
  a60=(a49+a60);
  a62=(a0-a30);
  a63=(a62*a2);
  a64=cos(a3);
  a65=(a63*a64);
  a66=(a17-a50);
  a67=(a66*a2);
  a68=sin(a3);
  a69=(a67*a68);
  a65=(a65+a69);
  a69=(a0-a30);
  a70=casadi_sq(a69);
  a71=(a17-a50);
  a72=casadi_sq(a71);
  a70=(a70+a72);
  a70=sqrt(a70);
  a65=(a65/a70);
  a30=(a0-a30);
  a72=casadi_sq(a30);
  a50=(a17-a50);
  a73=casadi_sq(a50);
  a72=(a72+a73);
  a72=sqrt(a72);
  a73=(a72-a59);
  a59=(a59+a31);
  a73=(a73/a59);
  a73=(a65+a73);
  a73=(a33*a73);
  a60=(a60-a73);
  if (res[0]!=0) res[0][1]=a60;
  a60=arg[3]? arg[3][10] : 0;
  a73=arg[3]? arg[3][13] : 0;
  a73=(a1*a73);
  a73=(a60+a73);
  a74=(a5-a73);
  a75=(a74*a9);
  a76=cos(a14);
  a77=(a75*a76);
  a78=arg[3]? arg[3][11] : 0;
  a79=arg[3]? arg[3][14] : 0;
  a79=(a1*a79);
  a79=(a78+a79);
  a80=(a19-a79);
  a81=(a80*a9);
  a82=sin(a14);
  a83=(a81*a82);
  a77=(a77+a83);
  a83=(a5-a73);
  a84=casadi_sq(a83);
  a85=(a19-a79);
  a86=casadi_sq(a85);
  a84=(a84+a86);
  a84=sqrt(a84);
  a77=(a77/a84);
  a73=(a5-a73);
  a86=casadi_sq(a73);
  a79=(a19-a79);
  a87=casadi_sq(a79);
  a86=(a86+a87);
  a86=sqrt(a86);
  a87=arg[3]? arg[3][12] : 0;
  a88=(a86-a87);
  a89=(a87+a31);
  a88=(a88/a89);
  a88=(a77+a88);
  a90=(a0-a60);
  a91=(a90*a2);
  a92=cos(a3);
  a93=(a91*a92);
  a94=(a17-a78);
  a95=(a94*a2);
  a96=sin(a3);
  a97=(a95*a96);
  a93=(a93+a97);
  a97=(a0-a60);
  a98=casadi_sq(a97);
  a99=(a17-a78);
  a100=casadi_sq(a99);
  a98=(a98+a100);
  a98=sqrt(a98);
  a93=(a93/a98);
  a60=(a0-a60);
  a100=casadi_sq(a60);
  a78=(a17-a78);
  a101=casadi_sq(a78);
  a100=(a100+a101);
  a100=sqrt(a100);
  a101=(a100-a87);
  a87=(a87+a31);
  a101=(a101/a87);
  a101=(a93+a101);
  a101=(a33*a101);
  a88=(a88-a101);
  if (res[0]!=0) res[0][2]=a88;
  a88=arg[3]? arg[3][15] : 0;
  a101=arg[3]? arg[3][18] : 0;
  a101=(a1*a101);
  a101=(a88+a101);
  a102=(a5-a101);
  a103=(a102*a9);
  a104=cos(a14);
  a105=(a103*a104);
  a106=arg[3]? arg[3][16] : 0;
  a107=arg[3]? arg[3][19] : 0;
  a107=(a1*a107);
  a107=(a106+a107);
  a108=(a19-a107);
  a109=(a108*a9);
  a110=sin(a14);
  a111=(a109*a110);
  a105=(a105+a111);
  a111=(a5-a101);
  a112=casadi_sq(a111);
  a113=(a19-a107);
  a114=casadi_sq(a113);
  a112=(a112+a114);
  a112=sqrt(a112);
  a105=(a105/a112);
  a101=(a5-a101);
  a114=casadi_sq(a101);
  a107=(a19-a107);
  a115=casadi_sq(a107);
  a114=(a114+a115);
  a114=sqrt(a114);
  a115=arg[3]? arg[3][17] : 0;
  a116=(a114-a115);
  a117=(a115+a31);
  a116=(a116/a117);
  a116=(a105+a116);
  a118=(a0-a88);
  a119=(a118*a2);
  a120=cos(a3);
  a121=(a119*a120);
  a122=(a17-a106);
  a123=(a122*a2);
  a124=sin(a3);
  a125=(a123*a124);
  a121=(a121+a125);
  a125=(a0-a88);
  a126=casadi_sq(a125);
  a127=(a17-a106);
  a128=casadi_sq(a127);
  a126=(a126+a128);
  a126=sqrt(a126);
  a121=(a121/a126);
  a88=(a0-a88);
  a128=casadi_sq(a88);
  a106=(a17-a106);
  a129=casadi_sq(a106);
  a128=(a128+a129);
  a128=sqrt(a128);
  a129=(a128-a115);
  a115=(a115+a31);
  a129=(a129/a115);
  a129=(a121+a129);
  a129=(a33*a129);
  a116=(a116-a129);
  if (res[0]!=0) res[0][3]=a116;
  a116=arg[3]? arg[3][20] : 0;
  a129=arg[3]? arg[3][23] : 0;
  a129=(a1*a129);
  a129=(a116+a129);
  a130=(a5-a129);
  a131=(a130*a9);
  a132=cos(a14);
  a133=(a131*a132);
  a134=arg[3]? arg[3][21] : 0;
  a135=arg[3]? arg[3][24] : 0;
  a135=(a1*a135);
  a135=(a134+a135);
  a136=(a19-a135);
  a137=(a136*a9);
  a138=sin(a14);
  a139=(a137*a138);
  a133=(a133+a139);
  a139=(a5-a129);
  a140=casadi_sq(a139);
  a141=(a19-a135);
  a142=casadi_sq(a141);
  a140=(a140+a142);
  a140=sqrt(a140);
  a133=(a133/a140);
  a5=(a5-a129);
  a129=casadi_sq(a5);
  a19=(a19-a135);
  a135=casadi_sq(a19);
  a129=(a129+a135);
  a129=sqrt(a129);
  a135=arg[3]? arg[3][22] : 0;
  a142=(a129-a135);
  a143=(a135+a31);
  a142=(a142/a143);
  a142=(a133+a142);
  a144=(a0-a116);
  a145=(a144*a2);
  a146=cos(a3);
  a147=(a145*a146);
  a148=(a17-a134);
  a149=(a148*a2);
  a150=sin(a3);
  a151=(a149*a150);
  a147=(a147+a151);
  a151=(a0-a116);
  a152=casadi_sq(a151);
  a153=(a17-a134);
  a154=casadi_sq(a153);
  a152=(a152+a154);
  a152=sqrt(a152);
  a147=(a147/a152);
  a0=(a0-a116);
  a116=casadi_sq(a0);
  a17=(a17-a134);
  a134=casadi_sq(a17);
  a116=(a116+a134);
  a116=sqrt(a116);
  a134=(a116-a135);
  a135=(a135+a31);
  a134=(a134/a135);
  a134=(a147+a134);
  a134=(a33*a134);
  a142=(a142-a134);
  if (res[0]!=0) res[0][4]=a142;
  a142=(a15*a9);
  a142=(a142/a26);
  a16=(a16/a26);
  a134=(a25/a26);
  a134=(a16*a134);
  a142=(a142-a134);
  a134=(a7/a28);
  a134=(a134/a32);
  a142=(a142+a134);
  a134=(a36*a2);
  a134=(a134/a42);
  a37=(a37/a42);
  a41=(a41/a42);
  a41=(a37*a41);
  a134=(a134-a41);
  a6=(a6/a44);
  a6=(a6/a29);
  a134=(a134+a6);
  a134=(a33*a134);
  a142=(a142-a134);
  if (res[1]!=0) res[1][0]=a142;
  a142=(a24*a9);
  a142=(a142/a26);
  a134=(a27/a26);
  a134=(a16*a134);
  a142=(a142-a134);
  a134=(a21/a28);
  a134=(a134/a32);
  a142=(a142+a134);
  a134=(a40*a2);
  a134=(a134/a42);
  a43=(a43/a42);
  a37=(a37*a43);
  a134=(a134-a37);
  a20=(a20/a44);
  a20=(a20/a29);
  a134=(a134+a20);
  a134=(a33*a134);
  a142=(a142-a134);
  if (res[1]!=0) res[1][1]=a142;
  a142=cos(a3);
  a142=(a2*a142);
  a142=(a1*a142);
  a134=(a9*a142);
  a134=(a24*a134);
  a20=cos(a14);
  a29=(a23*a20);
  a134=(a134+a29);
  a29=sin(a3);
  a29=(a2*a29);
  a29=(a1*a29);
  a44=(a9*a29);
  a44=(a15*a44);
  a37=sin(a14);
  a43=(a13*a37);
  a44=(a44+a43);
  a134=(a134-a44);
  a134=(a134/a26);
  a27=(a27+a27);
  a44=(a27*a142);
  a25=(a25+a25);
  a43=(a25*a29);
  a44=(a44-a43);
  a43=(a26+a26);
  a44=(a44/a43);
  a44=(a16*a44);
  a134=(a134-a44);
  a21=(a21+a21);
  a44=(a21*a142);
  a7=(a7+a7);
  a6=(a7*a29);
  a44=(a44-a6);
  a28=(a28+a28);
  a44=(a44/a28);
  a44=(a44/a32);
  a134=(a134+a44);
  a44=cos(a3);
  a39=(a39*a44);
  a44=sin(a3);
  a35=(a35*a44);
  a39=(a39-a35);
  a39=(a39/a42);
  a39=(a33*a39);
  a134=(a134-a39);
  if (res[1]!=0) res[1][2]=a134;
  a4=(a1*a4);
  a134=(a9*a4);
  a39=1.;
  a35=2.7777777777777776e-02;
  a12=(a2/a12);
  a11=(a11*a12);
  a11=(a2*a11);
  a11=(a11+a10);
  a35=(a35*a11);
  a35=(a1*a35);
  a39=(a39-a35);
  a35=(a8*a39);
  a134=(a134+a35);
  a134=(a15*a134);
  a18=(a1*a18);
  a35=(a9*a18);
  a11=(a22*a39);
  a35=(a35+a11);
  a35=(a24*a35);
  a134=(a134+a35);
  a134=(a134/a26);
  a25=(a25*a4);
  a27=(a27*a18);
  a25=(a25+a27);
  a25=(a25/a43);
  a16=(a16*a25);
  a134=(a134-a16);
  a7=(a7*a4);
  a21=(a21*a18);
  a7=(a7+a21);
  a7=(a7/a28);
  a7=(a7/a32);
  a134=(a134+a7);
  a36=(a36*a34);
  a40=(a40*a38);
  a36=(a36+a40);
  a36=(a36/a42);
  a36=(a33*a36);
  a134=(a134-a36);
  if (res[1]!=0) res[1][3]=a134;
  a20=(a1*a20);
  a23=(a23*a20);
  a37=(a1*a37);
  a13=(a13*a37);
  a23=(a23-a13);
  a23=(a23/a26);
  if (res[1]!=0) res[1][4]=a23;
  a23=5.5555555555555558e-03;
  a13=(a23*a8);
  a13=(a15*a13);
  a37=(a23*a22);
  a37=(a24*a37);
  a13=(a13+a37);
  a13=(a13/a26);
  if (res[1]!=0) res[1][5]=a13;
  a8=(a23*a8);
  a15=(a15*a8);
  a22=(a23*a22);
  a24=(a24*a22);
  a15=(a15+a24);
  a15=(a15/a26);
  if (res[1]!=0) res[1][6]=a15;
  a15=(a48*a9);
  a15=(a15/a56);
  a49=(a49/a56);
  a26=(a55/a56);
  a26=(a49*a26);
  a15=(a15-a26);
  a26=(a45/a58);
  a26=(a26/a61);
  a15=(a15+a26);
  a26=(a64*a2);
  a26=(a26/a70);
  a65=(a65/a70);
  a69=(a69/a70);
  a69=(a65*a69);
  a26=(a26-a69);
  a30=(a30/a72);
  a30=(a30/a59);
  a26=(a26+a30);
  a26=(a33*a26);
  a15=(a15-a26);
  if (res[1]!=0) res[1][7]=a15;
  a15=(a54*a9);
  a15=(a15/a56);
  a26=(a57/a56);
  a26=(a49*a26);
  a15=(a15-a26);
  a26=(a51/a58);
  a26=(a26/a61);
  a15=(a15+a26);
  a26=(a68*a2);
  a26=(a26/a70);
  a71=(a71/a70);
  a65=(a65*a71);
  a26=(a26-a65);
  a50=(a50/a72);
  a50=(a50/a59);
  a26=(a26+a50);
  a26=(a33*a26);
  a15=(a15-a26);
  if (res[1]!=0) res[1][8]=a15;
  a15=(a9*a142);
  a15=(a54*a15);
  a26=cos(a14);
  a50=(a53*a26);
  a15=(a15+a50);
  a50=(a9*a29);
  a50=(a48*a50);
  a59=sin(a14);
  a72=(a47*a59);
  a50=(a50+a72);
  a15=(a15-a50);
  a15=(a15/a56);
  a57=(a57+a57);
  a50=(a57*a142);
  a55=(a55+a55);
  a72=(a55*a29);
  a50=(a50-a72);
  a72=(a56+a56);
  a50=(a50/a72);
  a50=(a49*a50);
  a15=(a15-a50);
  a51=(a51+a51);
  a50=(a51*a142);
  a45=(a45+a45);
  a65=(a45*a29);
  a50=(a50-a65);
  a58=(a58+a58);
  a50=(a50/a58);
  a50=(a50/a61);
  a15=(a15+a50);
  a50=cos(a3);
  a67=(a67*a50);
  a50=sin(a3);
  a63=(a63*a50);
  a67=(a67-a63);
  a67=(a67/a70);
  a67=(a33*a67);
  a15=(a15-a67);
  if (res[1]!=0) res[1][9]=a15;
  a15=(a9*a4);
  a67=(a46*a39);
  a15=(a15+a67);
  a15=(a48*a15);
  a67=(a9*a18);
  a63=(a52*a39);
  a67=(a67+a63);
  a67=(a54*a67);
  a15=(a15+a67);
  a15=(a15/a56);
  a55=(a55*a4);
  a57=(a57*a18);
  a55=(a55+a57);
  a55=(a55/a72);
  a49=(a49*a55);
  a15=(a15-a49);
  a45=(a45*a4);
  a51=(a51*a18);
  a45=(a45+a51);
  a45=(a45/a58);
  a45=(a45/a61);
  a15=(a15+a45);
  a64=(a64*a62);
  a68=(a68*a66);
  a64=(a64+a68);
  a64=(a64/a70);
  a64=(a33*a64);
  a15=(a15-a64);
  if (res[1]!=0) res[1][10]=a15;
  a26=(a1*a26);
  a53=(a53*a26);
  a59=(a1*a59);
  a47=(a47*a59);
  a53=(a53-a47);
  a53=(a53/a56);
  if (res[1]!=0) res[1][11]=a53;
  a53=(a23*a46);
  a53=(a48*a53);
  a47=(a23*a52);
  a47=(a54*a47);
  a53=(a53+a47);
  a53=(a53/a56);
  if (res[1]!=0) res[1][12]=a53;
  a46=(a23*a46);
  a48=(a48*a46);
  a52=(a23*a52);
  a54=(a54*a52);
  a48=(a48+a54);
  a48=(a48/a56);
  if (res[1]!=0) res[1][13]=a48;
  a48=(a76*a9);
  a48=(a48/a84);
  a77=(a77/a84);
  a56=(a83/a84);
  a56=(a77*a56);
  a48=(a48-a56);
  a56=(a73/a86);
  a56=(a56/a89);
  a48=(a48+a56);
  a56=(a92*a2);
  a56=(a56/a98);
  a93=(a93/a98);
  a97=(a97/a98);
  a97=(a93*a97);
  a56=(a56-a97);
  a60=(a60/a100);
  a60=(a60/a87);
  a56=(a56+a60);
  a56=(a33*a56);
  a48=(a48-a56);
  if (res[1]!=0) res[1][14]=a48;
  a48=(a82*a9);
  a48=(a48/a84);
  a56=(a85/a84);
  a56=(a77*a56);
  a48=(a48-a56);
  a56=(a79/a86);
  a56=(a56/a89);
  a48=(a48+a56);
  a56=(a96*a2);
  a56=(a56/a98);
  a99=(a99/a98);
  a93=(a93*a99);
  a56=(a56-a93);
  a78=(a78/a100);
  a78=(a78/a87);
  a56=(a56+a78);
  a56=(a33*a56);
  a48=(a48-a56);
  if (res[1]!=0) res[1][15]=a48;
  a48=(a9*a142);
  a48=(a82*a48);
  a56=cos(a14);
  a78=(a81*a56);
  a48=(a48+a78);
  a78=(a9*a29);
  a78=(a76*a78);
  a87=sin(a14);
  a100=(a75*a87);
  a78=(a78+a100);
  a48=(a48-a78);
  a48=(a48/a84);
  a85=(a85+a85);
  a78=(a85*a142);
  a83=(a83+a83);
  a100=(a83*a29);
  a78=(a78-a100);
  a100=(a84+a84);
  a78=(a78/a100);
  a78=(a77*a78);
  a48=(a48-a78);
  a79=(a79+a79);
  a78=(a79*a142);
  a73=(a73+a73);
  a93=(a73*a29);
  a78=(a78-a93);
  a86=(a86+a86);
  a78=(a78/a86);
  a78=(a78/a89);
  a48=(a48+a78);
  a78=cos(a3);
  a95=(a95*a78);
  a78=sin(a3);
  a91=(a91*a78);
  a95=(a95-a91);
  a95=(a95/a98);
  a95=(a33*a95);
  a48=(a48-a95);
  if (res[1]!=0) res[1][16]=a48;
  a48=(a9*a4);
  a95=(a74*a39);
  a48=(a48+a95);
  a48=(a76*a48);
  a95=(a9*a18);
  a91=(a80*a39);
  a95=(a95+a91);
  a95=(a82*a95);
  a48=(a48+a95);
  a48=(a48/a84);
  a83=(a83*a4);
  a85=(a85*a18);
  a83=(a83+a85);
  a83=(a83/a100);
  a77=(a77*a83);
  a48=(a48-a77);
  a73=(a73*a4);
  a79=(a79*a18);
  a73=(a73+a79);
  a73=(a73/a86);
  a73=(a73/a89);
  a48=(a48+a73);
  a92=(a92*a90);
  a96=(a96*a94);
  a92=(a92+a96);
  a92=(a92/a98);
  a92=(a33*a92);
  a48=(a48-a92);
  if (res[1]!=0) res[1][17]=a48;
  a56=(a1*a56);
  a81=(a81*a56);
  a87=(a1*a87);
  a75=(a75*a87);
  a81=(a81-a75);
  a81=(a81/a84);
  if (res[1]!=0) res[1][18]=a81;
  a81=(a23*a74);
  a81=(a76*a81);
  a75=(a23*a80);
  a75=(a82*a75);
  a81=(a81+a75);
  a81=(a81/a84);
  if (res[1]!=0) res[1][19]=a81;
  a74=(a23*a74);
  a76=(a76*a74);
  a80=(a23*a80);
  a82=(a82*a80);
  a76=(a76+a82);
  a76=(a76/a84);
  if (res[1]!=0) res[1][20]=a76;
  a76=(a104*a9);
  a76=(a76/a112);
  a105=(a105/a112);
  a84=(a111/a112);
  a84=(a105*a84);
  a76=(a76-a84);
  a84=(a101/a114);
  a84=(a84/a117);
  a76=(a76+a84);
  a84=(a120*a2);
  a84=(a84/a126);
  a121=(a121/a126);
  a125=(a125/a126);
  a125=(a121*a125);
  a84=(a84-a125);
  a88=(a88/a128);
  a88=(a88/a115);
  a84=(a84+a88);
  a84=(a33*a84);
  a76=(a76-a84);
  if (res[1]!=0) res[1][21]=a76;
  a76=(a110*a9);
  a76=(a76/a112);
  a84=(a113/a112);
  a84=(a105*a84);
  a76=(a76-a84);
  a84=(a107/a114);
  a84=(a84/a117);
  a76=(a76+a84);
  a84=(a124*a2);
  a84=(a84/a126);
  a127=(a127/a126);
  a121=(a121*a127);
  a84=(a84-a121);
  a106=(a106/a128);
  a106=(a106/a115);
  a84=(a84+a106);
  a84=(a33*a84);
  a76=(a76-a84);
  if (res[1]!=0) res[1][22]=a76;
  a76=(a9*a142);
  a76=(a110*a76);
  a84=cos(a14);
  a106=(a109*a84);
  a76=(a76+a106);
  a106=(a9*a29);
  a106=(a104*a106);
  a115=sin(a14);
  a128=(a103*a115);
  a106=(a106+a128);
  a76=(a76-a106);
  a76=(a76/a112);
  a113=(a113+a113);
  a106=(a113*a142);
  a111=(a111+a111);
  a128=(a111*a29);
  a106=(a106-a128);
  a128=(a112+a112);
  a106=(a106/a128);
  a106=(a105*a106);
  a76=(a76-a106);
  a107=(a107+a107);
  a106=(a107*a142);
  a101=(a101+a101);
  a121=(a101*a29);
  a106=(a106-a121);
  a114=(a114+a114);
  a106=(a106/a114);
  a106=(a106/a117);
  a76=(a76+a106);
  a106=cos(a3);
  a123=(a123*a106);
  a106=sin(a3);
  a119=(a119*a106);
  a123=(a123-a119);
  a123=(a123/a126);
  a123=(a33*a123);
  a76=(a76-a123);
  if (res[1]!=0) res[1][23]=a76;
  a76=(a9*a4);
  a123=(a102*a39);
  a76=(a76+a123);
  a76=(a104*a76);
  a123=(a9*a18);
  a119=(a108*a39);
  a123=(a123+a119);
  a123=(a110*a123);
  a76=(a76+a123);
  a76=(a76/a112);
  a111=(a111*a4);
  a113=(a113*a18);
  a111=(a111+a113);
  a111=(a111/a128);
  a105=(a105*a111);
  a76=(a76-a105);
  a101=(a101*a4);
  a107=(a107*a18);
  a101=(a101+a107);
  a101=(a101/a114);
  a101=(a101/a117);
  a76=(a76+a101);
  a120=(a120*a118);
  a124=(a124*a122);
  a120=(a120+a124);
  a120=(a120/a126);
  a120=(a33*a120);
  a76=(a76-a120);
  if (res[1]!=0) res[1][24]=a76;
  a84=(a1*a84);
  a109=(a109*a84);
  a115=(a1*a115);
  a103=(a103*a115);
  a109=(a109-a103);
  a109=(a109/a112);
  if (res[1]!=0) res[1][25]=a109;
  a109=(a23*a102);
  a109=(a104*a109);
  a103=(a23*a108);
  a103=(a110*a103);
  a109=(a109+a103);
  a109=(a109/a112);
  if (res[1]!=0) res[1][26]=a109;
  a102=(a23*a102);
  a104=(a104*a102);
  a108=(a23*a108);
  a110=(a110*a108);
  a104=(a104+a110);
  a104=(a104/a112);
  if (res[1]!=0) res[1][27]=a104;
  a104=(a132*a9);
  a104=(a104/a140);
  a133=(a133/a140);
  a112=(a139/a140);
  a112=(a133*a112);
  a104=(a104-a112);
  a112=(a5/a129);
  a112=(a112/a143);
  a104=(a104+a112);
  a112=(a146*a2);
  a112=(a112/a152);
  a147=(a147/a152);
  a151=(a151/a152);
  a151=(a147*a151);
  a112=(a112-a151);
  a0=(a0/a116);
  a0=(a0/a135);
  a112=(a112+a0);
  a112=(a33*a112);
  a104=(a104-a112);
  if (res[1]!=0) res[1][28]=a104;
  a104=(a138*a9);
  a104=(a104/a140);
  a112=(a141/a140);
  a112=(a133*a112);
  a104=(a104-a112);
  a112=(a19/a129);
  a112=(a112/a143);
  a104=(a104+a112);
  a2=(a150*a2);
  a2=(a2/a152);
  a153=(a153/a152);
  a147=(a147*a153);
  a2=(a2-a147);
  a17=(a17/a116);
  a17=(a17/a135);
  a2=(a2+a17);
  a2=(a33*a2);
  a104=(a104-a2);
  if (res[1]!=0) res[1][29]=a104;
  a104=(a9*a142);
  a104=(a138*a104);
  a2=cos(a14);
  a17=(a137*a2);
  a104=(a104+a17);
  a17=(a9*a29);
  a17=(a132*a17);
  a14=sin(a14);
  a135=(a131*a14);
  a17=(a17+a135);
  a104=(a104-a17);
  a104=(a104/a140);
  a141=(a141+a141);
  a17=(a141*a142);
  a139=(a139+a139);
  a135=(a139*a29);
  a17=(a17-a135);
  a135=(a140+a140);
  a17=(a17/a135);
  a17=(a133*a17);
  a104=(a104-a17);
  a19=(a19+a19);
  a142=(a19*a142);
  a5=(a5+a5);
  a29=(a5*a29);
  a142=(a142-a29);
  a129=(a129+a129);
  a142=(a142/a129);
  a142=(a142/a143);
  a104=(a104+a142);
  a142=cos(a3);
  a149=(a149*a142);
  a3=sin(a3);
  a145=(a145*a3);
  a149=(a149-a145);
  a149=(a149/a152);
  a149=(a33*a149);
  a104=(a104-a149);
  if (res[1]!=0) res[1][30]=a104;
  a104=(a9*a4);
  a149=(a130*a39);
  a104=(a104+a149);
  a104=(a132*a104);
  a9=(a9*a18);
  a39=(a136*a39);
  a9=(a9+a39);
  a9=(a138*a9);
  a104=(a104+a9);
  a104=(a104/a140);
  a139=(a139*a4);
  a141=(a141*a18);
  a139=(a139+a141);
  a139=(a139/a135);
  a133=(a133*a139);
  a104=(a104-a133);
  a5=(a5*a4);
  a19=(a19*a18);
  a5=(a5+a19);
  a5=(a5/a129);
  a5=(a5/a143);
  a104=(a104+a5);
  a146=(a146*a144);
  a150=(a150*a148);
  a146=(a146+a150);
  a146=(a146/a152);
  a33=(a33*a146);
  a104=(a104-a33);
  if (res[1]!=0) res[1][31]=a104;
  a2=(a1*a2);
  a137=(a137*a2);
  a1=(a1*a14);
  a131=(a131*a1);
  a137=(a137-a131);
  a137=(a137/a140);
  if (res[1]!=0) res[1][32]=a137;
  a137=(a23*a130);
  a137=(a132*a137);
  a131=(a23*a136);
  a131=(a138*a131);
  a137=(a137+a131);
  a137=(a137/a140);
  if (res[1]!=0) res[1][33]=a137;
  a130=(a23*a130);
  a132=(a132*a130);
  a23=(a23*a136);
  a138=(a138*a23);
  a132=(a132+a138);
  a132=(a132/a140);
  if (res[1]!=0) res[1][34]=a132;
  return 0;
}

CASADI_SYMBOL_EXPORT int ship_constr_h_fun_jac_uxt_zt(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int ship_constr_h_fun_jac_uxt_zt_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int ship_constr_h_fun_jac_uxt_zt_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void ship_constr_h_fun_jac_uxt_zt_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int ship_constr_h_fun_jac_uxt_zt_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void ship_constr_h_fun_jac_uxt_zt_release(int mem) {
}

CASADI_SYMBOL_EXPORT void ship_constr_h_fun_jac_uxt_zt_incref(void) {
}

CASADI_SYMBOL_EXPORT void ship_constr_h_fun_jac_uxt_zt_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int ship_constr_h_fun_jac_uxt_zt_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int ship_constr_h_fun_jac_uxt_zt_n_out(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_real ship_constr_h_fun_jac_uxt_zt_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* ship_constr_h_fun_jac_uxt_zt_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* ship_constr_h_fun_jac_uxt_zt_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* ship_constr_h_fun_jac_uxt_zt_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    case 3: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* ship_constr_h_fun_jac_uxt_zt_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s4;
    case 1: return casadi_s5;
    case 2: return casadi_s6;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int ship_constr_h_fun_jac_uxt_zt_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4;
  if (sz_res) *sz_res = 3;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
