/* This file was automatically generated by CasADi 3.6.4.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) ship_constr_h_fun_jac_uxt_zt_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[11] = {7, 1, 0, 7, 0, 1, 2, 3, 4, 5, 6};
static const casadi_int casadi_s1[6] = {2, 1, 0, 2, 0, 1};
static const casadi_int casadi_s2[3] = {0, 0, 0};
static const casadi_int casadi_s3[29] = {25, 1, 0, 25, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24};
static const casadi_int casadi_s4[9] = {5, 1, 0, 5, 0, 1, 2, 3, 4};
static const casadi_int casadi_s5[43] = {9, 5, 0, 7, 14, 21, 28, 35, 2, 3, 4, 5, 6, 7, 8, 2, 3, 4, 5, 6, 7, 8, 2, 3, 4, 5, 6, 7, 8, 2, 3, 4, 5, 6, 7, 8, 2, 3, 4, 5, 6, 7, 8};
static const casadi_int casadi_s6[3] = {5, 0, 0};

/* ship_constr_h_fun_jac_uxt_zt:(i0[7],i1[2],i2[],i3[25])->(o0[5],o1[9x5,35nz],o2[5x0]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a10, a100, a101, a102, a103, a104, a105, a106, a107, a108, a109, a11, a110, a111, a112, a113, a114, a115, a116, a117, a118, a119, a12, a120, a121, a122, a123, a124, a125, a126, a127, a128, a129, a13, a130, a131, a132, a133, a134, a135, a136, a137, a138, a139, a14, a140, a141, a142, a143, a144, a145, a146, a147, a148, a149, a15, a150, a151, a152, a153, a154, a155, a16, a17, a18, a19, a2, a20, a21, a22, a23, a24, a25, a26, a27, a28, a29, a3, a30, a31, a32, a33, a34, a35, a36, a37, a38, a39, a4, a40, a41, a42, a43, a44, a45, a46, a47, a48, a49, a5, a50, a51, a52, a53, a54, a55, a56, a57, a58, a59, a6, a60, a61, a62, a63, a64, a65, a66, a67, a68, a69, a7, a70, a71, a72, a73, a74, a75, a76, a77, a78, a79, a8, a80, a81, a82, a83, a84, a85, a86, a87, a88, a89, a9, a90, a91, a92, a93, a94, a95, a96, a97, a98, a99;
  a0=arg[0]? arg[0][0] : 0;
  a1=2.0000000000000001e-01;
  a2=arg[0]? arg[0][3] : 0;
  a3=arg[0]? arg[0][2] : 0;
  a4=cos(a3);
  a5=(a2*a4);
  a5=(a1*a5);
  a5=(a0+a5);
  a6=arg[3]? arg[3][0] : 0;
  a7=arg[3]? arg[3][3] : 0;
  a7=(a1*a7);
  a7=(a6+a7);
  a8=(a5-a7);
  a9=arg[0]? arg[0][5] : 0;
  a10=arg[0]? arg[0][6] : 0;
  a9=(a9+a10);
  a10=10.;
  a11=1.6899999999999999e+01;
  a12=casadi_sq(a2);
  a13=1.0000000000000001e-05;
  a12=(a12+a13);
  a12=sqrt(a12);
  a13=(a11*a12);
  a10=(a10+a13);
  a13=(a10*a2);
  a9=(a9-a13);
  a13=36.;
  a9=(a9/a13);
  a9=(a1*a9);
  a9=(a2+a9);
  a13=(a8*a9);
  a14=arg[0]? arg[0][4] : 0;
  a14=(a1*a14);
  a14=(a3+a14);
  a15=cos(a14);
  a16=(a13*a15);
  a17=arg[0]? arg[0][1] : 0;
  a18=sin(a3);
  a19=(a2*a18);
  a19=(a1*a19);
  a19=(a17+a19);
  a20=arg[3]? arg[3][1] : 0;
  a21=arg[3]? arg[3][4] : 0;
  a21=(a1*a21);
  a21=(a20+a21);
  a22=(a19-a21);
  a23=(a22*a9);
  a24=sin(a14);
  a25=(a23*a24);
  a16=(a16+a25);
  a25=(a5-a7);
  a26=casadi_sq(a25);
  a27=(a19-a21);
  a28=casadi_sq(a27);
  a26=(a26+a28);
  a26=sqrt(a26);
  a16=(a16/a26);
  a28=1.5000000000000000e+00;
  a29=arg[3]? arg[3][2] : 0;
  a30=1.0000000000000000e-04;
  a31=(a29+a30);
  a31=(a28/a31);
  a7=(a5-a7);
  a32=casadi_sq(a7);
  a21=(a19-a21);
  a33=casadi_sq(a21);
  a32=(a32+a33);
  a32=sqrt(a32);
  a33=(a32-a29);
  a33=(a31*a33);
  a33=(a16+a33);
  a34=9.7999999999999998e-01;
  a35=(a0-a6);
  a36=(a35*a2);
  a37=cos(a3);
  a38=(a36*a37);
  a39=(a17-a20);
  a40=(a39*a2);
  a41=sin(a3);
  a42=(a40*a41);
  a38=(a38+a42);
  a42=(a0-a6);
  a43=casadi_sq(a42);
  a44=(a17-a20);
  a45=casadi_sq(a44);
  a43=(a43+a45);
  a43=sqrt(a43);
  a38=(a38/a43);
  a45=(a29+a30);
  a45=(a28/a45);
  a6=(a0-a6);
  a46=casadi_sq(a6);
  a20=(a17-a20);
  a47=casadi_sq(a20);
  a46=(a46+a47);
  a46=sqrt(a46);
  a29=(a46-a29);
  a29=(a45*a29);
  a29=(a38+a29);
  a29=(a34*a29);
  a33=(a33-a29);
  if (res[0]!=0) res[0][0]=a33;
  a33=arg[3]? arg[3][5] : 0;
  a29=arg[3]? arg[3][8] : 0;
  a29=(a1*a29);
  a29=(a33+a29);
  a47=(a5-a29);
  a48=(a47*a9);
  a49=cos(a14);
  a50=(a48*a49);
  a51=arg[3]? arg[3][6] : 0;
  a52=arg[3]? arg[3][9] : 0;
  a52=(a1*a52);
  a52=(a51+a52);
  a53=(a19-a52);
  a54=(a53*a9);
  a55=sin(a14);
  a56=(a54*a55);
  a50=(a50+a56);
  a56=(a5-a29);
  a57=casadi_sq(a56);
  a58=(a19-a52);
  a59=casadi_sq(a58);
  a57=(a57+a59);
  a57=sqrt(a57);
  a50=(a50/a57);
  a59=arg[3]? arg[3][7] : 0;
  a60=(a59+a30);
  a60=(a28/a60);
  a29=(a5-a29);
  a61=casadi_sq(a29);
  a52=(a19-a52);
  a62=casadi_sq(a52);
  a61=(a61+a62);
  a61=sqrt(a61);
  a62=(a61-a59);
  a62=(a60*a62);
  a62=(a50+a62);
  a63=(a0-a33);
  a64=(a63*a2);
  a65=cos(a3);
  a66=(a64*a65);
  a67=(a17-a51);
  a68=(a67*a2);
  a69=sin(a3);
  a70=(a68*a69);
  a66=(a66+a70);
  a70=(a0-a33);
  a71=casadi_sq(a70);
  a72=(a17-a51);
  a73=casadi_sq(a72);
  a71=(a71+a73);
  a71=sqrt(a71);
  a66=(a66/a71);
  a73=(a59+a30);
  a73=(a28/a73);
  a33=(a0-a33);
  a74=casadi_sq(a33);
  a51=(a17-a51);
  a75=casadi_sq(a51);
  a74=(a74+a75);
  a74=sqrt(a74);
  a59=(a74-a59);
  a59=(a73*a59);
  a59=(a66+a59);
  a59=(a34*a59);
  a62=(a62-a59);
  if (res[0]!=0) res[0][1]=a62;
  a62=arg[3]? arg[3][10] : 0;
  a59=arg[3]? arg[3][13] : 0;
  a59=(a1*a59);
  a59=(a62+a59);
  a75=(a5-a59);
  a76=(a75*a9);
  a77=cos(a14);
  a78=(a76*a77);
  a79=arg[3]? arg[3][11] : 0;
  a80=arg[3]? arg[3][14] : 0;
  a80=(a1*a80);
  a80=(a79+a80);
  a81=(a19-a80);
  a82=(a81*a9);
  a83=sin(a14);
  a84=(a82*a83);
  a78=(a78+a84);
  a84=(a5-a59);
  a85=casadi_sq(a84);
  a86=(a19-a80);
  a87=casadi_sq(a86);
  a85=(a85+a87);
  a85=sqrt(a85);
  a78=(a78/a85);
  a87=arg[3]? arg[3][12] : 0;
  a88=(a87+a30);
  a88=(a28/a88);
  a59=(a5-a59);
  a89=casadi_sq(a59);
  a80=(a19-a80);
  a90=casadi_sq(a80);
  a89=(a89+a90);
  a89=sqrt(a89);
  a90=(a89-a87);
  a90=(a88*a90);
  a90=(a78+a90);
  a91=(a0-a62);
  a92=(a91*a2);
  a93=cos(a3);
  a94=(a92*a93);
  a95=(a17-a79);
  a96=(a95*a2);
  a97=sin(a3);
  a98=(a96*a97);
  a94=(a94+a98);
  a98=(a0-a62);
  a99=casadi_sq(a98);
  a100=(a17-a79);
  a101=casadi_sq(a100);
  a99=(a99+a101);
  a99=sqrt(a99);
  a94=(a94/a99);
  a101=(a87+a30);
  a101=(a28/a101);
  a62=(a0-a62);
  a102=casadi_sq(a62);
  a79=(a17-a79);
  a103=casadi_sq(a79);
  a102=(a102+a103);
  a102=sqrt(a102);
  a87=(a102-a87);
  a87=(a101*a87);
  a87=(a94+a87);
  a87=(a34*a87);
  a90=(a90-a87);
  if (res[0]!=0) res[0][2]=a90;
  a90=arg[3]? arg[3][15] : 0;
  a87=arg[3]? arg[3][18] : 0;
  a87=(a1*a87);
  a87=(a90+a87);
  a103=(a5-a87);
  a104=(a103*a9);
  a105=cos(a14);
  a106=(a104*a105);
  a107=arg[3]? arg[3][16] : 0;
  a108=arg[3]? arg[3][19] : 0;
  a108=(a1*a108);
  a108=(a107+a108);
  a109=(a19-a108);
  a110=(a109*a9);
  a111=sin(a14);
  a112=(a110*a111);
  a106=(a106+a112);
  a112=(a5-a87);
  a113=casadi_sq(a112);
  a114=(a19-a108);
  a115=casadi_sq(a114);
  a113=(a113+a115);
  a113=sqrt(a113);
  a106=(a106/a113);
  a115=arg[3]? arg[3][17] : 0;
  a116=(a115+a30);
  a116=(a28/a116);
  a87=(a5-a87);
  a117=casadi_sq(a87);
  a108=(a19-a108);
  a118=casadi_sq(a108);
  a117=(a117+a118);
  a117=sqrt(a117);
  a118=(a117-a115);
  a118=(a116*a118);
  a118=(a106+a118);
  a119=(a0-a90);
  a120=(a119*a2);
  a121=cos(a3);
  a122=(a120*a121);
  a123=(a17-a107);
  a124=(a123*a2);
  a125=sin(a3);
  a126=(a124*a125);
  a122=(a122+a126);
  a126=(a0-a90);
  a127=casadi_sq(a126);
  a128=(a17-a107);
  a129=casadi_sq(a128);
  a127=(a127+a129);
  a127=sqrt(a127);
  a122=(a122/a127);
  a129=(a115+a30);
  a129=(a28/a129);
  a90=(a0-a90);
  a130=casadi_sq(a90);
  a107=(a17-a107);
  a131=casadi_sq(a107);
  a130=(a130+a131);
  a130=sqrt(a130);
  a115=(a130-a115);
  a115=(a129*a115);
  a115=(a122+a115);
  a115=(a34*a115);
  a118=(a118-a115);
  if (res[0]!=0) res[0][3]=a118;
  a118=arg[3]? arg[3][20] : 0;
  a115=arg[3]? arg[3][23] : 0;
  a115=(a1*a115);
  a115=(a118+a115);
  a131=(a5-a115);
  a132=(a131*a9);
  a133=cos(a14);
  a134=(a132*a133);
  a135=arg[3]? arg[3][21] : 0;
  a136=arg[3]? arg[3][24] : 0;
  a136=(a1*a136);
  a136=(a135+a136);
  a137=(a19-a136);
  a138=(a137*a9);
  a139=sin(a14);
  a140=(a138*a139);
  a134=(a134+a140);
  a140=(a5-a115);
  a141=casadi_sq(a140);
  a142=(a19-a136);
  a143=casadi_sq(a142);
  a141=(a141+a143);
  a141=sqrt(a141);
  a134=(a134/a141);
  a143=arg[3]? arg[3][22] : 0;
  a144=(a143+a30);
  a144=(a28/a144);
  a5=(a5-a115);
  a115=casadi_sq(a5);
  a19=(a19-a136);
  a136=casadi_sq(a19);
  a115=(a115+a136);
  a115=sqrt(a115);
  a136=(a115-a143);
  a136=(a144*a136);
  a136=(a134+a136);
  a145=(a0-a118);
  a146=(a145*a2);
  a147=cos(a3);
  a148=(a146*a147);
  a149=(a17-a135);
  a150=(a149*a2);
  a151=sin(a3);
  a152=(a150*a151);
  a148=(a148+a152);
  a152=(a0-a118);
  a153=casadi_sq(a152);
  a154=(a17-a135);
  a155=casadi_sq(a154);
  a153=(a153+a155);
  a153=sqrt(a153);
  a148=(a148/a153);
  a30=(a143+a30);
  a28=(a28/a30);
  a0=(a0-a118);
  a118=casadi_sq(a0);
  a17=(a17-a135);
  a135=casadi_sq(a17);
  a118=(a118+a135);
  a118=sqrt(a118);
  a143=(a118-a143);
  a143=(a28*a143);
  a143=(a148+a143);
  a143=(a34*a143);
  a136=(a136-a143);
  if (res[0]!=0) res[0][4]=a136;
  a136=(a15*a9);
  a136=(a136/a26);
  a16=(a16/a26);
  a143=(a25/a26);
  a143=(a16*a143);
  a136=(a136-a143);
  a143=(a7/a32);
  a143=(a31*a143);
  a136=(a136+a143);
  a143=(a37*a2);
  a143=(a143/a43);
  a38=(a38/a43);
  a42=(a42/a43);
  a42=(a38*a42);
  a143=(a143-a42);
  a6=(a6/a46);
  a6=(a45*a6);
  a143=(a143+a6);
  a143=(a34*a143);
  a136=(a136-a143);
  if (res[1]!=0) res[1][0]=a136;
  a136=(a24*a9);
  a136=(a136/a26);
  a143=(a27/a26);
  a143=(a16*a143);
  a136=(a136-a143);
  a143=(a21/a32);
  a143=(a31*a143);
  a136=(a136+a143);
  a143=(a41*a2);
  a143=(a143/a43);
  a44=(a44/a43);
  a38=(a38*a44);
  a143=(a143-a38);
  a20=(a20/a46);
  a45=(a45*a20);
  a143=(a143+a45);
  a143=(a34*a143);
  a136=(a136-a143);
  if (res[1]!=0) res[1][1]=a136;
  a136=cos(a3);
  a136=(a2*a136);
  a136=(a1*a136);
  a143=(a9*a136);
  a143=(a24*a143);
  a45=cos(a14);
  a20=(a23*a45);
  a143=(a143+a20);
  a20=sin(a3);
  a20=(a2*a20);
  a20=(a1*a20);
  a46=(a9*a20);
  a46=(a15*a46);
  a38=sin(a14);
  a44=(a13*a38);
  a46=(a46+a44);
  a143=(a143-a46);
  a143=(a143/a26);
  a27=(a27+a27);
  a46=(a27*a136);
  a25=(a25+a25);
  a44=(a25*a20);
  a46=(a46-a44);
  a44=(a26+a26);
  a46=(a46/a44);
  a46=(a16*a46);
  a143=(a143-a46);
  a21=(a21+a21);
  a46=(a21*a136);
  a7=(a7+a7);
  a6=(a7*a20);
  a46=(a46-a6);
  a32=(a32+a32);
  a46=(a46/a32);
  a46=(a31*a46);
  a143=(a143+a46);
  a46=cos(a3);
  a40=(a40*a46);
  a46=sin(a3);
  a36=(a36*a46);
  a40=(a40-a36);
  a40=(a40/a43);
  a40=(a34*a40);
  a143=(a143-a40);
  if (res[1]!=0) res[1][2]=a143;
  a4=(a1*a4);
  a143=(a9*a4);
  a40=1.;
  a36=2.7777777777777776e-02;
  a12=(a2/a12);
  a11=(a11*a12);
  a11=(a2*a11);
  a11=(a11+a10);
  a36=(a36*a11);
  a36=(a1*a36);
  a40=(a40-a36);
  a36=(a8*a40);
  a143=(a143+a36);
  a143=(a15*a143);
  a18=(a1*a18);
  a36=(a9*a18);
  a11=(a22*a40);
  a36=(a36+a11);
  a36=(a24*a36);
  a143=(a143+a36);
  a143=(a143/a26);
  a25=(a25*a4);
  a27=(a27*a18);
  a25=(a25+a27);
  a25=(a25/a44);
  a16=(a16*a25);
  a143=(a143-a16);
  a7=(a7*a4);
  a21=(a21*a18);
  a7=(a7+a21);
  a7=(a7/a32);
  a31=(a31*a7);
  a143=(a143+a31);
  a37=(a37*a35);
  a41=(a41*a39);
  a37=(a37+a41);
  a37=(a37/a43);
  a37=(a34*a37);
  a143=(a143-a37);
  if (res[1]!=0) res[1][3]=a143;
  a45=(a1*a45);
  a23=(a23*a45);
  a38=(a1*a38);
  a13=(a13*a38);
  a23=(a23-a13);
  a23=(a23/a26);
  if (res[1]!=0) res[1][4]=a23;
  a23=5.5555555555555558e-03;
  a13=(a23*a8);
  a13=(a15*a13);
  a38=(a23*a22);
  a38=(a24*a38);
  a13=(a13+a38);
  a13=(a13/a26);
  if (res[1]!=0) res[1][5]=a13;
  a8=(a23*a8);
  a15=(a15*a8);
  a22=(a23*a22);
  a24=(a24*a22);
  a15=(a15+a24);
  a15=(a15/a26);
  if (res[1]!=0) res[1][6]=a15;
  a15=(a49*a9);
  a15=(a15/a57);
  a50=(a50/a57);
  a26=(a56/a57);
  a26=(a50*a26);
  a15=(a15-a26);
  a26=(a29/a61);
  a26=(a60*a26);
  a15=(a15+a26);
  a26=(a65*a2);
  a26=(a26/a71);
  a66=(a66/a71);
  a70=(a70/a71);
  a70=(a66*a70);
  a26=(a26-a70);
  a33=(a33/a74);
  a33=(a73*a33);
  a26=(a26+a33);
  a26=(a34*a26);
  a15=(a15-a26);
  if (res[1]!=0) res[1][7]=a15;
  a15=(a55*a9);
  a15=(a15/a57);
  a26=(a58/a57);
  a26=(a50*a26);
  a15=(a15-a26);
  a26=(a52/a61);
  a26=(a60*a26);
  a15=(a15+a26);
  a26=(a69*a2);
  a26=(a26/a71);
  a72=(a72/a71);
  a66=(a66*a72);
  a26=(a26-a66);
  a51=(a51/a74);
  a73=(a73*a51);
  a26=(a26+a73);
  a26=(a34*a26);
  a15=(a15-a26);
  if (res[1]!=0) res[1][8]=a15;
  a15=(a9*a136);
  a15=(a55*a15);
  a26=cos(a14);
  a73=(a54*a26);
  a15=(a15+a73);
  a73=(a9*a20);
  a73=(a49*a73);
  a51=sin(a14);
  a74=(a48*a51);
  a73=(a73+a74);
  a15=(a15-a73);
  a15=(a15/a57);
  a58=(a58+a58);
  a73=(a58*a136);
  a56=(a56+a56);
  a74=(a56*a20);
  a73=(a73-a74);
  a74=(a57+a57);
  a73=(a73/a74);
  a73=(a50*a73);
  a15=(a15-a73);
  a52=(a52+a52);
  a73=(a52*a136);
  a29=(a29+a29);
  a66=(a29*a20);
  a73=(a73-a66);
  a61=(a61+a61);
  a73=(a73/a61);
  a73=(a60*a73);
  a15=(a15+a73);
  a73=cos(a3);
  a68=(a68*a73);
  a73=sin(a3);
  a64=(a64*a73);
  a68=(a68-a64);
  a68=(a68/a71);
  a68=(a34*a68);
  a15=(a15-a68);
  if (res[1]!=0) res[1][9]=a15;
  a15=(a9*a4);
  a68=(a47*a40);
  a15=(a15+a68);
  a15=(a49*a15);
  a68=(a9*a18);
  a64=(a53*a40);
  a68=(a68+a64);
  a68=(a55*a68);
  a15=(a15+a68);
  a15=(a15/a57);
  a56=(a56*a4);
  a58=(a58*a18);
  a56=(a56+a58);
  a56=(a56/a74);
  a50=(a50*a56);
  a15=(a15-a50);
  a29=(a29*a4);
  a52=(a52*a18);
  a29=(a29+a52);
  a29=(a29/a61);
  a60=(a60*a29);
  a15=(a15+a60);
  a65=(a65*a63);
  a69=(a69*a67);
  a65=(a65+a69);
  a65=(a65/a71);
  a65=(a34*a65);
  a15=(a15-a65);
  if (res[1]!=0) res[1][10]=a15;
  a26=(a1*a26);
  a54=(a54*a26);
  a51=(a1*a51);
  a48=(a48*a51);
  a54=(a54-a48);
  a54=(a54/a57);
  if (res[1]!=0) res[1][11]=a54;
  a54=(a23*a47);
  a54=(a49*a54);
  a48=(a23*a53);
  a48=(a55*a48);
  a54=(a54+a48);
  a54=(a54/a57);
  if (res[1]!=0) res[1][12]=a54;
  a47=(a23*a47);
  a49=(a49*a47);
  a53=(a23*a53);
  a55=(a55*a53);
  a49=(a49+a55);
  a49=(a49/a57);
  if (res[1]!=0) res[1][13]=a49;
  a49=(a77*a9);
  a49=(a49/a85);
  a78=(a78/a85);
  a57=(a84/a85);
  a57=(a78*a57);
  a49=(a49-a57);
  a57=(a59/a89);
  a57=(a88*a57);
  a49=(a49+a57);
  a57=(a93*a2);
  a57=(a57/a99);
  a94=(a94/a99);
  a98=(a98/a99);
  a98=(a94*a98);
  a57=(a57-a98);
  a62=(a62/a102);
  a62=(a101*a62);
  a57=(a57+a62);
  a57=(a34*a57);
  a49=(a49-a57);
  if (res[1]!=0) res[1][14]=a49;
  a49=(a83*a9);
  a49=(a49/a85);
  a57=(a86/a85);
  a57=(a78*a57);
  a49=(a49-a57);
  a57=(a80/a89);
  a57=(a88*a57);
  a49=(a49+a57);
  a57=(a97*a2);
  a57=(a57/a99);
  a100=(a100/a99);
  a94=(a94*a100);
  a57=(a57-a94);
  a79=(a79/a102);
  a101=(a101*a79);
  a57=(a57+a101);
  a57=(a34*a57);
  a49=(a49-a57);
  if (res[1]!=0) res[1][15]=a49;
  a49=(a9*a136);
  a49=(a83*a49);
  a57=cos(a14);
  a101=(a82*a57);
  a49=(a49+a101);
  a101=(a9*a20);
  a101=(a77*a101);
  a79=sin(a14);
  a102=(a76*a79);
  a101=(a101+a102);
  a49=(a49-a101);
  a49=(a49/a85);
  a86=(a86+a86);
  a101=(a86*a136);
  a84=(a84+a84);
  a102=(a84*a20);
  a101=(a101-a102);
  a102=(a85+a85);
  a101=(a101/a102);
  a101=(a78*a101);
  a49=(a49-a101);
  a80=(a80+a80);
  a101=(a80*a136);
  a59=(a59+a59);
  a94=(a59*a20);
  a101=(a101-a94);
  a89=(a89+a89);
  a101=(a101/a89);
  a101=(a88*a101);
  a49=(a49+a101);
  a101=cos(a3);
  a96=(a96*a101);
  a101=sin(a3);
  a92=(a92*a101);
  a96=(a96-a92);
  a96=(a96/a99);
  a96=(a34*a96);
  a49=(a49-a96);
  if (res[1]!=0) res[1][16]=a49;
  a49=(a9*a4);
  a96=(a75*a40);
  a49=(a49+a96);
  a49=(a77*a49);
  a96=(a9*a18);
  a92=(a81*a40);
  a96=(a96+a92);
  a96=(a83*a96);
  a49=(a49+a96);
  a49=(a49/a85);
  a84=(a84*a4);
  a86=(a86*a18);
  a84=(a84+a86);
  a84=(a84/a102);
  a78=(a78*a84);
  a49=(a49-a78);
  a59=(a59*a4);
  a80=(a80*a18);
  a59=(a59+a80);
  a59=(a59/a89);
  a88=(a88*a59);
  a49=(a49+a88);
  a93=(a93*a91);
  a97=(a97*a95);
  a93=(a93+a97);
  a93=(a93/a99);
  a93=(a34*a93);
  a49=(a49-a93);
  if (res[1]!=0) res[1][17]=a49;
  a57=(a1*a57);
  a82=(a82*a57);
  a79=(a1*a79);
  a76=(a76*a79);
  a82=(a82-a76);
  a82=(a82/a85);
  if (res[1]!=0) res[1][18]=a82;
  a82=(a23*a75);
  a82=(a77*a82);
  a76=(a23*a81);
  a76=(a83*a76);
  a82=(a82+a76);
  a82=(a82/a85);
  if (res[1]!=0) res[1][19]=a82;
  a75=(a23*a75);
  a77=(a77*a75);
  a81=(a23*a81);
  a83=(a83*a81);
  a77=(a77+a83);
  a77=(a77/a85);
  if (res[1]!=0) res[1][20]=a77;
  a77=(a105*a9);
  a77=(a77/a113);
  a106=(a106/a113);
  a85=(a112/a113);
  a85=(a106*a85);
  a77=(a77-a85);
  a85=(a87/a117);
  a85=(a116*a85);
  a77=(a77+a85);
  a85=(a121*a2);
  a85=(a85/a127);
  a122=(a122/a127);
  a126=(a126/a127);
  a126=(a122*a126);
  a85=(a85-a126);
  a90=(a90/a130);
  a90=(a129*a90);
  a85=(a85+a90);
  a85=(a34*a85);
  a77=(a77-a85);
  if (res[1]!=0) res[1][21]=a77;
  a77=(a111*a9);
  a77=(a77/a113);
  a85=(a114/a113);
  a85=(a106*a85);
  a77=(a77-a85);
  a85=(a108/a117);
  a85=(a116*a85);
  a77=(a77+a85);
  a85=(a125*a2);
  a85=(a85/a127);
  a128=(a128/a127);
  a122=(a122*a128);
  a85=(a85-a122);
  a107=(a107/a130);
  a129=(a129*a107);
  a85=(a85+a129);
  a85=(a34*a85);
  a77=(a77-a85);
  if (res[1]!=0) res[1][22]=a77;
  a77=(a9*a136);
  a77=(a111*a77);
  a85=cos(a14);
  a129=(a110*a85);
  a77=(a77+a129);
  a129=(a9*a20);
  a129=(a105*a129);
  a107=sin(a14);
  a130=(a104*a107);
  a129=(a129+a130);
  a77=(a77-a129);
  a77=(a77/a113);
  a114=(a114+a114);
  a129=(a114*a136);
  a112=(a112+a112);
  a130=(a112*a20);
  a129=(a129-a130);
  a130=(a113+a113);
  a129=(a129/a130);
  a129=(a106*a129);
  a77=(a77-a129);
  a108=(a108+a108);
  a129=(a108*a136);
  a87=(a87+a87);
  a122=(a87*a20);
  a129=(a129-a122);
  a117=(a117+a117);
  a129=(a129/a117);
  a129=(a116*a129);
  a77=(a77+a129);
  a129=cos(a3);
  a124=(a124*a129);
  a129=sin(a3);
  a120=(a120*a129);
  a124=(a124-a120);
  a124=(a124/a127);
  a124=(a34*a124);
  a77=(a77-a124);
  if (res[1]!=0) res[1][23]=a77;
  a77=(a9*a4);
  a124=(a103*a40);
  a77=(a77+a124);
  a77=(a105*a77);
  a124=(a9*a18);
  a120=(a109*a40);
  a124=(a124+a120);
  a124=(a111*a124);
  a77=(a77+a124);
  a77=(a77/a113);
  a112=(a112*a4);
  a114=(a114*a18);
  a112=(a112+a114);
  a112=(a112/a130);
  a106=(a106*a112);
  a77=(a77-a106);
  a87=(a87*a4);
  a108=(a108*a18);
  a87=(a87+a108);
  a87=(a87/a117);
  a116=(a116*a87);
  a77=(a77+a116);
  a121=(a121*a119);
  a125=(a125*a123);
  a121=(a121+a125);
  a121=(a121/a127);
  a121=(a34*a121);
  a77=(a77-a121);
  if (res[1]!=0) res[1][24]=a77;
  a85=(a1*a85);
  a110=(a110*a85);
  a107=(a1*a107);
  a104=(a104*a107);
  a110=(a110-a104);
  a110=(a110/a113);
  if (res[1]!=0) res[1][25]=a110;
  a110=(a23*a103);
  a110=(a105*a110);
  a104=(a23*a109);
  a104=(a111*a104);
  a110=(a110+a104);
  a110=(a110/a113);
  if (res[1]!=0) res[1][26]=a110;
  a103=(a23*a103);
  a105=(a105*a103);
  a109=(a23*a109);
  a111=(a111*a109);
  a105=(a105+a111);
  a105=(a105/a113);
  if (res[1]!=0) res[1][27]=a105;
  a105=(a133*a9);
  a105=(a105/a141);
  a134=(a134/a141);
  a113=(a140/a141);
  a113=(a134*a113);
  a105=(a105-a113);
  a113=(a5/a115);
  a113=(a144*a113);
  a105=(a105+a113);
  a113=(a147*a2);
  a113=(a113/a153);
  a148=(a148/a153);
  a152=(a152/a153);
  a152=(a148*a152);
  a113=(a113-a152);
  a0=(a0/a118);
  a0=(a28*a0);
  a113=(a113+a0);
  a113=(a34*a113);
  a105=(a105-a113);
  if (res[1]!=0) res[1][28]=a105;
  a105=(a139*a9);
  a105=(a105/a141);
  a113=(a142/a141);
  a113=(a134*a113);
  a105=(a105-a113);
  a113=(a19/a115);
  a113=(a144*a113);
  a105=(a105+a113);
  a2=(a151*a2);
  a2=(a2/a153);
  a154=(a154/a153);
  a148=(a148*a154);
  a2=(a2-a148);
  a17=(a17/a118);
  a28=(a28*a17);
  a2=(a2+a28);
  a2=(a34*a2);
  a105=(a105-a2);
  if (res[1]!=0) res[1][29]=a105;
  a105=(a9*a136);
  a105=(a139*a105);
  a2=cos(a14);
  a28=(a138*a2);
  a105=(a105+a28);
  a28=(a9*a20);
  a28=(a133*a28);
  a14=sin(a14);
  a17=(a132*a14);
  a28=(a28+a17);
  a105=(a105-a28);
  a105=(a105/a141);
  a142=(a142+a142);
  a28=(a142*a136);
  a140=(a140+a140);
  a17=(a140*a20);
  a28=(a28-a17);
  a17=(a141+a141);
  a28=(a28/a17);
  a28=(a134*a28);
  a105=(a105-a28);
  a19=(a19+a19);
  a136=(a19*a136);
  a5=(a5+a5);
  a20=(a5*a20);
  a136=(a136-a20);
  a115=(a115+a115);
  a136=(a136/a115);
  a136=(a144*a136);
  a105=(a105+a136);
  a136=cos(a3);
  a150=(a150*a136);
  a3=sin(a3);
  a146=(a146*a3);
  a150=(a150-a146);
  a150=(a150/a153);
  a150=(a34*a150);
  a105=(a105-a150);
  if (res[1]!=0) res[1][30]=a105;
  a105=(a9*a4);
  a150=(a131*a40);
  a105=(a105+a150);
  a105=(a133*a105);
  a9=(a9*a18);
  a40=(a137*a40);
  a9=(a9+a40);
  a9=(a139*a9);
  a105=(a105+a9);
  a105=(a105/a141);
  a140=(a140*a4);
  a142=(a142*a18);
  a140=(a140+a142);
  a140=(a140/a17);
  a134=(a134*a140);
  a105=(a105-a134);
  a5=(a5*a4);
  a19=(a19*a18);
  a5=(a5+a19);
  a5=(a5/a115);
  a144=(a144*a5);
  a105=(a105+a144);
  a147=(a147*a145);
  a151=(a151*a149);
  a147=(a147+a151);
  a147=(a147/a153);
  a34=(a34*a147);
  a105=(a105-a34);
  if (res[1]!=0) res[1][31]=a105;
  a2=(a1*a2);
  a138=(a138*a2);
  a1=(a1*a14);
  a132=(a132*a1);
  a138=(a138-a132);
  a138=(a138/a141);
  if (res[1]!=0) res[1][32]=a138;
  a138=(a23*a131);
  a138=(a133*a138);
  a132=(a23*a137);
  a132=(a139*a132);
  a138=(a138+a132);
  a138=(a138/a141);
  if (res[1]!=0) res[1][33]=a138;
  a131=(a23*a131);
  a133=(a133*a131);
  a23=(a23*a137);
  a139=(a139*a23);
  a133=(a133+a139);
  a133=(a133/a141);
  if (res[1]!=0) res[1][34]=a133;
  return 0;
}

CASADI_SYMBOL_EXPORT int ship_constr_h_fun_jac_uxt_zt(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int ship_constr_h_fun_jac_uxt_zt_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int ship_constr_h_fun_jac_uxt_zt_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void ship_constr_h_fun_jac_uxt_zt_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int ship_constr_h_fun_jac_uxt_zt_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void ship_constr_h_fun_jac_uxt_zt_release(int mem) {
}

CASADI_SYMBOL_EXPORT void ship_constr_h_fun_jac_uxt_zt_incref(void) {
}

CASADI_SYMBOL_EXPORT void ship_constr_h_fun_jac_uxt_zt_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int ship_constr_h_fun_jac_uxt_zt_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int ship_constr_h_fun_jac_uxt_zt_n_out(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_real ship_constr_h_fun_jac_uxt_zt_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* ship_constr_h_fun_jac_uxt_zt_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* ship_constr_h_fun_jac_uxt_zt_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* ship_constr_h_fun_jac_uxt_zt_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    case 3: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* ship_constr_h_fun_jac_uxt_zt_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s4;
    case 1: return casadi_s5;
    case 2: return casadi_s6;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int ship_constr_h_fun_jac_uxt_zt_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4;
  if (sz_res) *sz_res = 3;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
