/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) heron_impl_dae_fun_jac_x_xdot_u_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[12] = {8, 1, 0, 8, 0, 1, 2, 3, 4, 5, 6, 7};
static const casadi_int casadi_s1[6] = {2, 1, 0, 2, 0, 1};
static const casadi_int casadi_s2[3] = {0, 0, 0};
static const casadi_int casadi_s3[10] = {6, 1, 0, 6, 0, 1, 2, 3, 4, 5};
static const casadi_int casadi_s4[29] = {8, 8, 0, 0, 0, 2, 5, 9, 14, 16, 18, 0, 1, 0, 1, 3, 0, 1, 4, 5, 0, 1, 2, 4, 5, 3, 5, 3, 5};
static const casadi_int casadi_s5[19] = {8, 8, 0, 1, 2, 3, 4, 5, 6, 7, 8, 0, 1, 2, 3, 4, 5, 6, 7};
static const casadi_int casadi_s6[7] = {8, 2, 0, 1, 2, 6, 7};

/* heron_impl_dae_fun_jac_x_xdot_u:(i0[8],i1[8],i2[2],i3[],i4[],i5[6])->(o0[8],o1[8x8,18nz],o2[8x8,8nz],o3[8x2,2nz]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a10, a11, a12, a13, a14, a15, a16, a17, a18, a19, a2, a20, a21, a22, a23, a3, a4, a5, a6, a7, a8, a9;
  a0=arg[1]? arg[1][0] : 0;
  a1=arg[0]? arg[0][3] : 0;
  a2=arg[0]? arg[0][2] : 0;
  a3=cos(a2);
  a4=(a1*a3);
  a5=arg[0]? arg[0][4] : 0;
  a6=sin(a2);
  a7=(a5*a6);
  a4=(a4-a7);
  a7=arg[0]? arg[0][5] : 0;
  a8=sin(a2);
  a9=(a7*a8);
  a4=(a4-a9);
  a0=(a0-a4);
  if (res[0]!=0) res[0][0]=a0;
  a0=arg[1]? arg[1][1] : 0;
  a4=sin(a2);
  a9=(a1*a4);
  a10=cos(a2);
  a11=(a5*a10);
  a9=(a9+a11);
  a11=cos(a2);
  a12=(a7*a11);
  a9=(a9+a12);
  a0=(a0-a9);
  if (res[0]!=0) res[0][1]=a0;
  a0=arg[1]? arg[1][2] : 0;
  a0=(a0-a7);
  if (res[0]!=0) res[0][2]=a0;
  a0=arg[1]? arg[1][3] : 0;
  a9=arg[0]? arg[0][6] : 0;
  a12=arg[0]? arg[0][7] : 0;
  a13=(a9+a12);
  a14=8.9148999999999994e+00;
  a14=(a14*a1);
  a13=(a13-a14);
  a14=1.1210100000000001e+01;
  a15=casadi_sq(a1);
  a16=1.0000000000000001e-05;
  a15=(a15+a16);
  a15=sqrt(a15);
  a17=(a14*a15);
  a18=(a17*a1);
  a13=(a13-a18);
  a18=3.7758000000000003e+01;
  a13=(a13/a18);
  a0=(a0-a13);
  if (res[0]!=0) res[0][3]=a0;
  a0=arg[1]? arg[1][4] : 0;
  a13=-15.;
  a19=(a13*a5);
  a20=3.;
  a21=casadi_sq(a5);
  a21=(a21+a16);
  a21=sqrt(a21);
  a16=(a20*a21);
  a22=(a16*a5);
  a19=(a19-a22);
  a22=6.;
  a23=(a22*a7);
  a19=(a19-a23);
  a19=(a19/a18);
  a0=(a0-a19);
  if (res[0]!=0) res[0][4]=a0;
  a0=arg[1]? arg[1][5] : 0;
  a19=2.9999999999999999e-01;
  a12=(a12-a9);
  a19=(a19*a12);
  a12=1.6954200000000000e+01;
  a12=(a12*a7);
  a19=(a19-a12);
  a12=1.2896599999999999e+01;
  a9=(a12*a7);
  a18=(a9*a7);
  a23=(a18*a7);
  a19=(a19-a23);
  a22=(a22*a5);
  a19=(a19-a22);
  a22=1.8350000000000001e+01;
  a19=(a19/a22);
  a0=(a0-a19);
  if (res[0]!=0) res[0][5]=a0;
  a0=arg[1]? arg[1][6] : 0;
  a19=arg[2]? arg[2][0] : 0;
  a0=(a0-a19);
  if (res[0]!=0) res[0][6]=a0;
  a0=arg[1]? arg[1][7] : 0;
  a19=arg[2]? arg[2][1] : 0;
  a0=(a0-a19);
  if (res[0]!=0) res[0][7]=a0;
  a0=sin(a2);
  a0=(a1*a0);
  a19=cos(a2);
  a19=(a5*a19);
  a0=(a0+a19);
  a19=cos(a2);
  a19=(a7*a19);
  a0=(a0+a19);
  if (res[1]!=0) res[1][0]=a0;
  a0=cos(a2);
  a0=(a1*a0);
  a19=sin(a2);
  a19=(a5*a19);
  a0=(a0-a19);
  a2=sin(a2);
  a2=(a7*a2);
  a0=(a0-a2);
  a0=(-a0);
  if (res[1]!=0) res[1][1]=a0;
  a3=(-a3);
  if (res[1]!=0) res[1][2]=a3;
  a4=(-a4);
  if (res[1]!=0) res[1][3]=a4;
  a4=2.6484453625721698e-02;
  a3=-8.9148999999999994e+00;
  a15=(a1/a15);
  a14=(a14*a15);
  a1=(a1*a14);
  a1=(a1+a17);
  a3=(a3-a1);
  a3=(a4*a3);
  a3=(-a3);
  if (res[1]!=0) res[1][4]=a3;
  if (res[1]!=0) res[1][5]=a6;
  a10=(-a10);
  if (res[1]!=0) res[1][6]=a10;
  a21=(a5/a21);
  a20=(a20*a21);
  a5=(a5*a20);
  a5=(a5+a16);
  a13=(a13-a5);
  a4=(a4*a13);
  a4=(-a4);
  if (res[1]!=0) res[1][7]=a4;
  a4=3.2697547683923700e-01;
  if (res[1]!=0) res[1][8]=a4;
  if (res[1]!=0) res[1][9]=a8;
  a11=(-a11);
  if (res[1]!=0) res[1][10]=a11;
  a11=-1.;
  if (res[1]!=0) res[1][11]=a11;
  a8=1.5890672175433018e-01;
  if (res[1]!=0) res[1][12]=a8;
  a8=5.4495912806539502e-02;
  a4=-1.6954200000000000e+01;
  a12=(a12*a7);
  a12=(a12+a9);
  a7=(a7*a12);
  a7=(a7+a18);
  a4=(a4-a7);
  a8=(a8*a4);
  a8=(-a8);
  if (res[1]!=0) res[1][13]=a8;
  a8=-2.6484453625721698e-02;
  if (res[1]!=0) res[1][14]=a8;
  a4=1.6348773841961851e-02;
  if (res[1]!=0) res[1][15]=a4;
  if (res[1]!=0) res[1][16]=a8;
  a8=-1.6348773841961851e-02;
  if (res[1]!=0) res[1][17]=a8;
  a8=1.;
  if (res[2]!=0) res[2][0]=a8;
  if (res[2]!=0) res[2][1]=a8;
  if (res[2]!=0) res[2][2]=a8;
  if (res[2]!=0) res[2][3]=a8;
  if (res[2]!=0) res[2][4]=a8;
  if (res[2]!=0) res[2][5]=a8;
  if (res[2]!=0) res[2][6]=a8;
  if (res[2]!=0) res[2][7]=a8;
  if (res[3]!=0) res[3][0]=a11;
  if (res[3]!=0) res[3][1]=a11;
  return 0;
}

CASADI_SYMBOL_EXPORT int heron_impl_dae_fun_jac_x_xdot_u(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int heron_impl_dae_fun_jac_x_xdot_u_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int heron_impl_dae_fun_jac_x_xdot_u_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void heron_impl_dae_fun_jac_x_xdot_u_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int heron_impl_dae_fun_jac_x_xdot_u_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void heron_impl_dae_fun_jac_x_xdot_u_release(int mem) {
}

CASADI_SYMBOL_EXPORT void heron_impl_dae_fun_jac_x_xdot_u_incref(void) {
}

CASADI_SYMBOL_EXPORT void heron_impl_dae_fun_jac_x_xdot_u_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int heron_impl_dae_fun_jac_x_xdot_u_n_in(void) { return 6;}

CASADI_SYMBOL_EXPORT casadi_int heron_impl_dae_fun_jac_x_xdot_u_n_out(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_real heron_impl_dae_fun_jac_x_xdot_u_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* heron_impl_dae_fun_jac_x_xdot_u_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    case 5: return "i5";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* heron_impl_dae_fun_jac_x_xdot_u_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    case 3: return "o3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* heron_impl_dae_fun_jac_x_xdot_u_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    case 2: return casadi_s1;
    case 3: return casadi_s2;
    case 4: return casadi_s2;
    case 5: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* heron_impl_dae_fun_jac_x_xdot_u_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s4;
    case 2: return casadi_s5;
    case 3: return casadi_s6;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int heron_impl_dae_fun_jac_x_xdot_u_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 6;
  if (sz_res) *sz_res = 4;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
