/* This file was automatically generated by CasADi 3.6.4.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) ship_expl_vde_forw_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[11] = {7, 1, 0, 7, 0, 1, 2, 3, 4, 5, 6};
static const casadi_int casadi_s1[59] = {7, 7, 0, 7, 14, 21, 28, 35, 42, 49, 0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6};
static const casadi_int casadi_s2[19] = {7, 2, 0, 7, 14, 0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6};
static const casadi_int casadi_s3[6] = {2, 1, 0, 2, 0, 1};
static const casadi_int casadi_s4[29] = {25, 1, 0, 25, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24};

/* ship_expl_vde_forw:(i0[7],i1[7x7],i2[7x2],i3[2],i4[25])->(o0[7],o1[7x7],o2[7x2]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a10, a11, a12, a13, a14, a15, a16, a17, a18, a19, a2, a20, a21, a22, a23, a3, a4, a5, a6, a7, a8, a9;
  a0=arg[0]? arg[0][3] : 0;
  a1=arg[0]? arg[0][2] : 0;
  a2=cos(a1);
  a3=(a0*a2);
  if (res[0]!=0) res[0][0]=a3;
  a3=sin(a1);
  a4=(a0*a3);
  if (res[0]!=0) res[0][1]=a4;
  a4=arg[0]? arg[0][4] : 0;
  if (res[0]!=0) res[0][2]=a4;
  a5=arg[0]? arg[0][5] : 0;
  a6=20.;
  a7=50.;
  a8=casadi_sq(a0);
  a9=1.0000000000000001e-05;
  a8=(a8+a9);
  a8=sqrt(a8);
  a10=(a7*a8);
  a6=(a6+a10);
  a10=(a6*a0);
  a5=(a5-a10);
  a10=100.;
  a5=(a5/a10);
  if (res[0]!=0) res[0][3]=a5;
  a5=arg[0]? arg[0][6] : 0;
  a11=25.;
  a12=casadi_sq(a4);
  a12=(a12+a9);
  a12=sqrt(a12);
  a9=(a10*a12);
  a11=(a11+a9);
  a9=(a11*a4);
  a5=(a5-a9);
  a9=500.;
  a5=(a5/a9);
  if (res[0]!=0) res[0][4]=a5;
  a5=arg[3]? arg[3][0] : 0;
  if (res[0]!=0) res[0][5]=a5;
  a5=arg[3]? arg[3][1] : 0;
  if (res[0]!=0) res[0][6]=a5;
  a5=arg[1]? arg[1][3] : 0;
  a9=(a2*a5);
  a13=sin(a1);
  a14=arg[1]? arg[1][2] : 0;
  a15=(a13*a14);
  a15=(a0*a15);
  a9=(a9-a15);
  if (res[1]!=0) res[1][0]=a9;
  a9=(a3*a5);
  a15=cos(a1);
  a14=(a15*a14);
  a14=(a0*a14);
  a9=(a9+a14);
  if (res[1]!=0) res[1][1]=a9;
  a9=arg[1]? arg[1][4] : 0;
  if (res[1]!=0) res[1][2]=a9;
  a14=1.0000000000000000e-02;
  a16=arg[1]? arg[1][5] : 0;
  a17=(a0+a0);
  a18=(a17*a5);
  a19=(a8+a8);
  a18=(a18/a19);
  a18=(a7*a18);
  a18=(a0*a18);
  a5=(a6*a5);
  a18=(a18+a5);
  a16=(a16-a18);
  a16=(a14*a16);
  if (res[1]!=0) res[1][3]=a16;
  a16=2.0000000000000000e-03;
  a18=arg[1]? arg[1][6] : 0;
  a5=(a4+a4);
  a20=(a5*a9);
  a21=(a12+a12);
  a20=(a20/a21);
  a20=(a10*a20);
  a20=(a4*a20);
  a9=(a11*a9);
  a20=(a20+a9);
  a18=(a18-a20);
  a18=(a16*a18);
  if (res[1]!=0) res[1][4]=a18;
  a18=0.;
  if (res[1]!=0) res[1][5]=a18;
  if (res[1]!=0) res[1][6]=a18;
  a20=arg[1]? arg[1][10] : 0;
  a9=(a2*a20);
  a22=arg[1]? arg[1][9] : 0;
  a23=(a13*a22);
  a23=(a0*a23);
  a9=(a9-a23);
  if (res[1]!=0) res[1][7]=a9;
  a9=(a3*a20);
  a22=(a15*a22);
  a22=(a0*a22);
  a9=(a9+a22);
  if (res[1]!=0) res[1][8]=a9;
  a9=arg[1]? arg[1][11] : 0;
  if (res[1]!=0) res[1][9]=a9;
  a22=arg[1]? arg[1][12] : 0;
  a23=(a17*a20);
  a23=(a23/a19);
  a23=(a7*a23);
  a23=(a0*a23);
  a20=(a6*a20);
  a23=(a23+a20);
  a22=(a22-a23);
  a22=(a14*a22);
  if (res[1]!=0) res[1][10]=a22;
  a22=arg[1]? arg[1][13] : 0;
  a23=(a5*a9);
  a23=(a23/a21);
  a23=(a10*a23);
  a23=(a4*a23);
  a9=(a11*a9);
  a23=(a23+a9);
  a22=(a22-a23);
  a22=(a16*a22);
  if (res[1]!=0) res[1][11]=a22;
  if (res[1]!=0) res[1][12]=a18;
  if (res[1]!=0) res[1][13]=a18;
  a22=arg[1]? arg[1][17] : 0;
  a23=(a2*a22);
  a9=arg[1]? arg[1][16] : 0;
  a20=(a13*a9);
  a20=(a0*a20);
  a23=(a23-a20);
  if (res[1]!=0) res[1][14]=a23;
  a23=(a3*a22);
  a9=(a15*a9);
  a9=(a0*a9);
  a23=(a23+a9);
  if (res[1]!=0) res[1][15]=a23;
  a23=arg[1]? arg[1][18] : 0;
  if (res[1]!=0) res[1][16]=a23;
  a9=arg[1]? arg[1][19] : 0;
  a20=(a17*a22);
  a20=(a20/a19);
  a20=(a7*a20);
  a20=(a0*a20);
  a22=(a6*a22);
  a20=(a20+a22);
  a9=(a9-a20);
  a9=(a14*a9);
  if (res[1]!=0) res[1][17]=a9;
  a9=arg[1]? arg[1][20] : 0;
  a20=(a5*a23);
  a20=(a20/a21);
  a20=(a10*a20);
  a20=(a4*a20);
  a23=(a11*a23);
  a20=(a20+a23);
  a9=(a9-a20);
  a9=(a16*a9);
  if (res[1]!=0) res[1][18]=a9;
  if (res[1]!=0) res[1][19]=a18;
  if (res[1]!=0) res[1][20]=a18;
  a9=arg[1]? arg[1][24] : 0;
  a20=(a2*a9);
  a23=arg[1]? arg[1][23] : 0;
  a22=(a13*a23);
  a22=(a0*a22);
  a20=(a20-a22);
  if (res[1]!=0) res[1][21]=a20;
  a20=(a3*a9);
  a23=(a15*a23);
  a23=(a0*a23);
  a20=(a20+a23);
  if (res[1]!=0) res[1][22]=a20;
  a20=arg[1]? arg[1][25] : 0;
  if (res[1]!=0) res[1][23]=a20;
  a23=arg[1]? arg[1][26] : 0;
  a22=(a17*a9);
  a22=(a22/a19);
  a22=(a7*a22);
  a22=(a0*a22);
  a9=(a6*a9);
  a22=(a22+a9);
  a23=(a23-a22);
  a23=(a14*a23);
  if (res[1]!=0) res[1][24]=a23;
  a23=arg[1]? arg[1][27] : 0;
  a22=(a5*a20);
  a22=(a22/a21);
  a22=(a10*a22);
  a22=(a4*a22);
  a20=(a11*a20);
  a22=(a22+a20);
  a23=(a23-a22);
  a23=(a16*a23);
  if (res[1]!=0) res[1][25]=a23;
  if (res[1]!=0) res[1][26]=a18;
  if (res[1]!=0) res[1][27]=a18;
  a23=arg[1]? arg[1][31] : 0;
  a22=(a2*a23);
  a20=arg[1]? arg[1][30] : 0;
  a9=(a13*a20);
  a9=(a0*a9);
  a22=(a22-a9);
  if (res[1]!=0) res[1][28]=a22;
  a22=(a3*a23);
  a20=(a15*a20);
  a20=(a0*a20);
  a22=(a22+a20);
  if (res[1]!=0) res[1][29]=a22;
  a22=arg[1]? arg[1][32] : 0;
  if (res[1]!=0) res[1][30]=a22;
  a20=arg[1]? arg[1][33] : 0;
  a9=(a17*a23);
  a9=(a9/a19);
  a9=(a7*a9);
  a9=(a0*a9);
  a23=(a6*a23);
  a9=(a9+a23);
  a20=(a20-a9);
  a20=(a14*a20);
  if (res[1]!=0) res[1][31]=a20;
  a20=arg[1]? arg[1][34] : 0;
  a9=(a5*a22);
  a9=(a9/a21);
  a9=(a10*a9);
  a9=(a4*a9);
  a22=(a11*a22);
  a9=(a9+a22);
  a20=(a20-a9);
  a20=(a16*a20);
  if (res[1]!=0) res[1][32]=a20;
  if (res[1]!=0) res[1][33]=a18;
  if (res[1]!=0) res[1][34]=a18;
  a20=arg[1]? arg[1][38] : 0;
  a9=(a2*a20);
  a22=arg[1]? arg[1][37] : 0;
  a23=(a13*a22);
  a23=(a0*a23);
  a9=(a9-a23);
  if (res[1]!=0) res[1][35]=a9;
  a9=(a3*a20);
  a22=(a15*a22);
  a22=(a0*a22);
  a9=(a9+a22);
  if (res[1]!=0) res[1][36]=a9;
  a9=arg[1]? arg[1][39] : 0;
  if (res[1]!=0) res[1][37]=a9;
  a22=arg[1]? arg[1][40] : 0;
  a23=(a17*a20);
  a23=(a23/a19);
  a23=(a7*a23);
  a23=(a0*a23);
  a20=(a6*a20);
  a23=(a23+a20);
  a22=(a22-a23);
  a22=(a14*a22);
  if (res[1]!=0) res[1][38]=a22;
  a22=arg[1]? arg[1][41] : 0;
  a23=(a5*a9);
  a23=(a23/a21);
  a23=(a10*a23);
  a23=(a4*a23);
  a9=(a11*a9);
  a23=(a23+a9);
  a22=(a22-a23);
  a22=(a16*a22);
  if (res[1]!=0) res[1][39]=a22;
  if (res[1]!=0) res[1][40]=a18;
  if (res[1]!=0) res[1][41]=a18;
  a22=arg[1]? arg[1][45] : 0;
  a23=(a2*a22);
  a9=arg[1]? arg[1][44] : 0;
  a13=(a13*a9);
  a13=(a0*a13);
  a23=(a23-a13);
  if (res[1]!=0) res[1][42]=a23;
  a23=(a3*a22);
  a15=(a15*a9);
  a15=(a0*a15);
  a23=(a23+a15);
  if (res[1]!=0) res[1][43]=a23;
  a23=arg[1]? arg[1][46] : 0;
  if (res[1]!=0) res[1][44]=a23;
  a15=arg[1]? arg[1][47] : 0;
  a17=(a17*a22);
  a17=(a17/a19);
  a17=(a7*a17);
  a17=(a0*a17);
  a22=(a6*a22);
  a17=(a17+a22);
  a15=(a15-a17);
  a15=(a14*a15);
  if (res[1]!=0) res[1][45]=a15;
  a15=arg[1]? arg[1][48] : 0;
  a5=(a5*a23);
  a5=(a5/a21);
  a5=(a10*a5);
  a5=(a4*a5);
  a23=(a11*a23);
  a5=(a5+a23);
  a15=(a15-a5);
  a15=(a16*a15);
  if (res[1]!=0) res[1][46]=a15;
  if (res[1]!=0) res[1][47]=a18;
  if (res[1]!=0) res[1][48]=a18;
  a15=arg[2]? arg[2][3] : 0;
  a5=(a2*a15);
  a23=sin(a1);
  a21=arg[2]? arg[2][2] : 0;
  a17=(a23*a21);
  a17=(a0*a17);
  a5=(a5-a17);
  if (res[2]!=0) res[2][0]=a5;
  a5=(a3*a15);
  a1=cos(a1);
  a21=(a1*a21);
  a21=(a0*a21);
  a5=(a5+a21);
  if (res[2]!=0) res[2][1]=a5;
  a5=arg[2]? arg[2][4] : 0;
  if (res[2]!=0) res[2][2]=a5;
  a21=arg[2]? arg[2][5] : 0;
  a17=(a0+a0);
  a22=(a17*a15);
  a8=(a8+a8);
  a22=(a22/a8);
  a22=(a7*a22);
  a22=(a0*a22);
  a15=(a6*a15);
  a22=(a22+a15);
  a21=(a21-a22);
  a21=(a14*a21);
  if (res[2]!=0) res[2][3]=a21;
  a21=arg[2]? arg[2][6] : 0;
  a22=(a4+a4);
  a15=(a22*a5);
  a12=(a12+a12);
  a15=(a15/a12);
  a15=(a10*a15);
  a15=(a4*a15);
  a5=(a11*a5);
  a15=(a15+a5);
  a21=(a21-a15);
  a21=(a16*a21);
  if (res[2]!=0) res[2][4]=a21;
  a21=1.;
  if (res[2]!=0) res[2][5]=a21;
  if (res[2]!=0) res[2][6]=a18;
  a15=arg[2]? arg[2][10] : 0;
  a2=(a2*a15);
  a5=arg[2]? arg[2][9] : 0;
  a23=(a23*a5);
  a23=(a0*a23);
  a2=(a2-a23);
  if (res[2]!=0) res[2][7]=a2;
  a3=(a3*a15);
  a1=(a1*a5);
  a1=(a0*a1);
  a3=(a3+a1);
  if (res[2]!=0) res[2][8]=a3;
  a3=arg[2]? arg[2][11] : 0;
  if (res[2]!=0) res[2][9]=a3;
  a1=arg[2]? arg[2][12] : 0;
  a17=(a17*a15);
  a17=(a17/a8);
  a7=(a7*a17);
  a0=(a0*a7);
  a6=(a6*a15);
  a0=(a0+a6);
  a1=(a1-a0);
  a14=(a14*a1);
  if (res[2]!=0) res[2][10]=a14;
  a14=arg[2]? arg[2][13] : 0;
  a22=(a22*a3);
  a22=(a22/a12);
  a10=(a10*a22);
  a4=(a4*a10);
  a11=(a11*a3);
  a4=(a4+a11);
  a14=(a14-a4);
  a16=(a16*a14);
  if (res[2]!=0) res[2][11]=a16;
  if (res[2]!=0) res[2][12]=a18;
  if (res[2]!=0) res[2][13]=a21;
  return 0;
}

CASADI_SYMBOL_EXPORT int ship_expl_vde_forw(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int ship_expl_vde_forw_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int ship_expl_vde_forw_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void ship_expl_vde_forw_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int ship_expl_vde_forw_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void ship_expl_vde_forw_release(int mem) {
}

CASADI_SYMBOL_EXPORT void ship_expl_vde_forw_incref(void) {
}

CASADI_SYMBOL_EXPORT void ship_expl_vde_forw_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int ship_expl_vde_forw_n_in(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_int ship_expl_vde_forw_n_out(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_real ship_expl_vde_forw_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* ship_expl_vde_forw_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* ship_expl_vde_forw_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* ship_expl_vde_forw_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    case 3: return casadi_s3;
    case 4: return casadi_s4;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* ship_expl_vde_forw_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int ship_expl_vde_forw_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5;
  if (sz_res) *sz_res = 3;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
