/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) simple_model_expl_ode_fun_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_c0 CASADI_PREFIX(c0)
#define casadi_c1 CASADI_PREFIX(c1)
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_mtimes CASADI_PREFIX(mtimes)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

void casadi_mtimes(const casadi_real* x, const casadi_int* sp_x, const casadi_real* y, const casadi_int* sp_y, casadi_real* z, const casadi_int* sp_z, casadi_real* w, casadi_int tr) {
  casadi_int ncol_x, ncol_y, ncol_z, cc;
  const casadi_int *colind_x, *row_x, *colind_y, *row_y, *colind_z, *row_z;
  ncol_x = sp_x[1];
  colind_x = sp_x+2; row_x = sp_x + 2 + ncol_x+1;
  ncol_y = sp_y[1];
  colind_y = sp_y+2; row_y = sp_y + 2 + ncol_y+1;
  ncol_z = sp_z[1];
  colind_z = sp_z+2; row_z = sp_z + 2 + ncol_z+1;
  if (tr) {
    for (cc=0; cc<ncol_z; ++cc) {
      casadi_int kk;
      for (kk=colind_y[cc]; kk<colind_y[cc+1]; ++kk) {
        w[row_y[kk]] = y[kk];
      }
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        casadi_int kk1;
        casadi_int rr = row_z[kk];
        for (kk1=colind_x[rr]; kk1<colind_x[rr+1]; ++kk1) {
          z[kk] += x[kk1] * w[row_x[kk1]];
        }
      }
    }
  } else {
    for (cc=0; cc<ncol_y; ++cc) {
      casadi_int kk;
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        w[row_z[kk]] = z[kk];
      }
      for (kk=colind_y[cc]; kk<colind_y[cc+1]; ++kk) {
        casadi_int kk1;
        casadi_int rr = row_y[kk];
        for (kk1=colind_x[rr]; kk1<colind_x[rr+1]; ++kk1) {
          w[row_x[kk1]] += x[kk1]*y[kk];
        }
      }
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        z[kk] = w[row_z[kk]];
      }
    }
  }
}

static const casadi_int casadi_s0[7] = {3, 1, 0, 3, 0, 1, 2};
static const casadi_int casadi_s1[9] = {3, 3, 0, 1, 2, 3, 0, 1, 2};
static const casadi_int casadi_s2[12] = {8, 1, 0, 8, 0, 1, 2, 3, 4, 5, 6, 7};
static const casadi_int casadi_s3[6] = {2, 1, 0, 2, 0, 1};
static const casadi_int casadi_s4[3] = {0, 0, 0};

static const casadi_real casadi_c0[3] = {2.5125628140703520e-04, 2.5125628140703520e-04, 5.0753692331117091e-05};
static const casadi_real casadi_c1[9] = {50., 0., 0., 0., 200., 0., 0., 0., 1281.};

/* simple_model_expl_ode_fun:(i0[8],i1[2],i2[])->(o0[8]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i, j, k;
  casadi_real *rr, *ss, *tt;
  const casadi_real *cs;
  casadi_real *w0=w+3, *w1=w+6, w2, w3, w4, *w5=w+12, *w6=w+15, *w7=w+18, *w8=w+27, w9, w10, w11, *w12=w+33, *w13=w+36, *w14=w+39, *w15=w+42, w16;
  /* #0: @0 = zeros(3x1) */
  casadi_clear(w0, 3);
  /* #1: @1 = 
  [[0.000251256, 00, 00], 
   [00, 0.000251256, 00], 
   [00, 00, 5.07537e-05]] */
  casadi_copy(casadi_c0, 3, w1);
  /* #2: @2 = input[0][6] */
  w2 = arg[0] ? arg[0][6] : 0;
  /* #3: @3 = input[0][7] */
  w3 = arg[0] ? arg[0][7] : 0;
  /* #4: @4 = -4 */
  w4 = -4.;
  /* #5: @4 = (@4*@3) */
  w4 *= w3;
  /* #6: @5 = vertcat(@2, @3, @4) */
  rr=w5;
  *rr++ = w2;
  *rr++ = w3;
  *rr++ = w4;
  /* #7: @6 = zeros(3x1) */
  casadi_clear(w6, 3);
  /* #8: @7 = 
  [[50, -0, -0], 
   [-0, 200, -0], 
   [-0, -0, 1281]] */
  casadi_copy(casadi_c1, 9, w7);
  /* #9: @2 = input[0][0] */
  w2 = arg[0] ? arg[0][0] : 0;
  /* #10: @3 = input[0][1] */
  w3 = arg[0] ? arg[0][1] : 0;
  /* #11: @4 = input[0][2] */
  w4 = arg[0] ? arg[0][2] : 0;
  /* #12: @8 = vertcat(@2, @3, @4) */
  rr=w8;
  *rr++ = w2;
  *rr++ = w3;
  *rr++ = w4;
  /* #13: @6 = mac(@7,@8,@6) */
  for (i=0, rr=w6; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w7+j, tt=w8+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #14: @5 = (@5-@6) */
  for (i=0, rr=w5, cs=w6; i<3; ++i) (*rr++) -= (*cs++);
  /* #15: @6 = zeros(3x1) */
  casadi_clear(w6, 3);
  /* #16: @9 = 0 */
  w9 = 0.;
  /* #17: @10 = 0 */
  w10 = 0.;
  /* #18: @11 = -3980 */
  w11 = -3980.;
  /* #19: @11 = (@11*@3) */
  w11 *= w3;
  /* #20: @12 = horzcat(@9, @10, @11) */
  rr=w12;
  *rr++ = w9;
  *rr++ = w10;
  *rr++ = w11;
  /* #21: @12 = @12' */
  /* #22: @9 = 0 */
  w9 = 0.;
  /* #23: @10 = 0 */
  w10 = 0.;
  /* #24: @11 = 3980 */
  w11 = 3980.;
  /* #25: @11 = (@11*@2) */
  w11 *= w2;
  /* #26: @13 = horzcat(@9, @10, @11) */
  rr=w13;
  *rr++ = w9;
  *rr++ = w10;
  *rr++ = w11;
  /* #27: @13 = @13' */
  /* #28: @9 = 3980 */
  w9 = 3980.;
  /* #29: @9 = (@9*@3) */
  w9 *= w3;
  /* #30: @10 = -3980 */
  w10 = -3980.;
  /* #31: @10 = (@10*@2) */
  w10 *= w2;
  /* #32: @11 = 0 */
  w11 = 0.;
  /* #33: @14 = horzcat(@9, @10, @11) */
  rr=w14;
  *rr++ = w9;
  *rr++ = w10;
  *rr++ = w11;
  /* #34: @14 = @14' */
  /* #35: @7 = horzcat(@12, @13, @14) */
  rr=w7;
  for (i=0, cs=w12; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w13; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w14; i<3; ++i) *rr++ = *cs++;
  /* #36: @15 = @7' */
  for (i=0, rr=w15, cs=w7; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #37: @6 = mac(@15,@8,@6) */
  for (i=0, rr=w6; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w15+j, tt=w8+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #38: @5 = (@5-@6) */
  for (i=0, rr=w5, cs=w6; i<3; ++i) (*rr++) -= (*cs++);
  /* #39: @0 = mac(@1,@5,@0) */
  casadi_mtimes(w1, casadi_s1, w5, casadi_s0, w0, casadi_s0, w, 0);
  /* #40: output[0][0] = @0 */
  casadi_copy(w0, 3, res[0]);
  /* #41: @9 = input[0][5] */
  w9 = arg[0] ? arg[0][5] : 0;
  /* #42: @10 = cos(@9) */
  w10 = cos( w9 );
  /* #43: @10 = (@2*@10) */
  w10  = (w2*w10);
  /* #44: @11 = sin(@9) */
  w11 = sin( w9 );
  /* #45: @11 = (@3*@11) */
  w11  = (w3*w11);
  /* #46: @10 = (@10-@11) */
  w10 -= w11;
  /* #47: @11 = 3.5 */
  w11 = 3.5000000000000000e+00;
  /* #48: @11 = (@11*@4) */
  w11 *= w4;
  /* #49: @16 = sin(@9) */
  w16 = sin( w9 );
  /* #50: @11 = (@11*@16) */
  w11 *= w16;
  /* #51: @10 = (@10-@11) */
  w10 -= w11;
  /* #52: @11 = 1 */
  w11 = 1.;
  /* #53: @10 = (@10-@11) */
  w10 -= w11;
  /* #54: output[0][1] = @10 */
  if (res[0]) res[0][3] = w10;
  /* #55: @10 = sin(@9) */
  w10 = sin( w9 );
  /* #56: @2 = (@2*@10) */
  w2 *= w10;
  /* #57: @10 = cos(@9) */
  w10 = cos( w9 );
  /* #58: @3 = (@3*@10) */
  w3 *= w10;
  /* #59: @2 = (@2+@3) */
  w2 += w3;
  /* #60: @3 = 3.5 */
  w3 = 3.5000000000000000e+00;
  /* #61: @3 = (@3*@4) */
  w3 *= w4;
  /* #62: @9 = cos(@9) */
  w9 = cos( w9 );
  /* #63: @3 = (@3*@9) */
  w3 *= w9;
  /* #64: @2 = (@2+@3) */
  w2 += w3;
  /* #65: output[0][2] = @2 */
  if (res[0]) res[0][4] = w2;
  /* #66: output[0][3] = @4 */
  if (res[0]) res[0][5] = w4;
  /* #67: @4 = input[1][0] */
  w4 = arg[1] ? arg[1][0] : 0;
  /* #68: output[0][4] = @4 */
  if (res[0]) res[0][6] = w4;
  /* #69: @4 = input[1][1] */
  w4 = arg[1] ? arg[1][1] : 0;
  /* #70: output[0][5] = @4 */
  if (res[0]) res[0][7] = w4;
  return 0;
}

CASADI_SYMBOL_EXPORT int simple_model_expl_ode_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int simple_model_expl_ode_fun_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int simple_model_expl_ode_fun_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void simple_model_expl_ode_fun_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int simple_model_expl_ode_fun_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void simple_model_expl_ode_fun_release(int mem) {
}

CASADI_SYMBOL_EXPORT void simple_model_expl_ode_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void simple_model_expl_ode_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int simple_model_expl_ode_fun_n_in(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_int simple_model_expl_ode_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real simple_model_expl_ode_fun_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* simple_model_expl_ode_fun_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* simple_model_expl_ode_fun_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* simple_model_expl_ode_fun_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s2;
    case 1: return casadi_s3;
    case 2: return casadi_s4;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* simple_model_expl_ode_fun_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int simple_model_expl_ode_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 6;
  if (sz_res) *sz_res = 2;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 52;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
