/* This file was automatically generated by CasADi 3.6.4.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) heron_constr_h_fun_jac_uxt_zt_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[11] = {7, 1, 0, 7, 0, 1, 2, 3, 4, 5, 6};
static const casadi_int casadi_s1[6] = {2, 1, 0, 2, 0, 1};
static const casadi_int casadi_s2[3] = {0, 0, 0};
static const casadi_int casadi_s3[19] = {15, 1, 0, 15, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14};
static const casadi_int casadi_s4[9] = {5, 1, 0, 5, 0, 1, 2, 3, 4};
static const casadi_int casadi_s5[43] = {9, 5, 0, 7, 14, 21, 28, 35, 2, 3, 4, 5, 6, 7, 8, 2, 3, 4, 5, 6, 7, 8, 2, 3, 4, 5, 6, 7, 8, 2, 3, 4, 5, 6, 7, 8, 2, 3, 4, 5, 6, 7, 8};
static const casadi_int casadi_s6[3] = {5, 0, 0};

/* heron_constr_h_fun_jac_uxt_zt:(i0[7],i1[2],i2[],i3[15])->(o0[5],o1[9x5,35nz],o2[5x0]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a10, a100, a101, a102, a103, a104, a105, a106, a107, a108, a109, a11, a110, a111, a112, a113, a114, a115, a116, a117, a118, a119, a12, a120, a121, a122, a123, a124, a125, a126, a127, a128, a129, a13, a130, a131, a132, a133, a134, a135, a136, a137, a138, a139, a14, a140, a141, a142, a143, a144, a145, a146, a147, a148, a149, a15, a150, a151, a152, a153, a154, a155, a156, a157, a158, a159, a16, a160, a161, a162, a163, a17, a18, a19, a2, a20, a21, a22, a23, a24, a25, a26, a27, a28, a29, a3, a30, a31, a32, a33, a34, a35, a36, a37, a38, a39, a4, a40, a41, a42, a43, a44, a45, a46, a47, a48, a49, a5, a50, a51, a52, a53, a54, a55, a56, a57, a58, a59, a6, a60, a61, a62, a63, a64, a65, a66, a67, a68, a69, a7, a70, a71, a72, a73, a74, a75, a76, a77, a78, a79, a8, a80, a81, a82, a83, a84, a85, a86, a87, a88, a89, a9, a90, a91, a92, a93, a94, a95, a96, a97, a98, a99;
  a0=arg[0]? arg[0][0] : 0;
  a1=2.0000000000000001e-01;
  a2=arg[0]? arg[0][3] : 0;
  a3=arg[0]? arg[0][2] : 0;
  a4=cos(a3);
  a5=(a2*a4);
  a5=(a1*a5);
  a6=(a0+a5);
  a7=arg[3]? arg[3][0] : 0;
  a6=(a6-a7);
  a8=arg[0]? arg[0][5] : 0;
  a9=arg[0]? arg[0][6] : 0;
  a8=(a8+a9);
  a9=10.;
  a10=1.6899999999999999e+01;
  a11=casadi_sq(a2);
  a12=1.0000000000000001e-05;
  a11=(a11+a12);
  a11=sqrt(a11);
  a12=(a10*a11);
  a9=(a9+a12);
  a12=(a9*a2);
  a8=(a8-a12);
  a12=36.;
  a8=(a8/a12);
  a8=(a1*a8);
  a12=(a2+a8);
  a13=(a6*a12);
  a14=arg[0]? arg[0][4] : 0;
  a14=(a1*a14);
  a15=(a3+a14);
  a16=cos(a15);
  a17=(a13*a16);
  a18=arg[0]? arg[0][1] : 0;
  a19=sin(a3);
  a20=(a2*a19);
  a20=(a1*a20);
  a21=(a18+a20);
  a22=arg[3]? arg[3][1] : 0;
  a21=(a21-a22);
  a23=(a2+a8);
  a24=(a21*a23);
  a25=(a3+a14);
  a26=sin(a25);
  a27=(a24*a26);
  a17=(a17+a27);
  a27=(a0+a5);
  a27=(a27-a7);
  a28=casadi_sq(a27);
  a29=(a18+a20);
  a29=(a29-a22);
  a30=casadi_sq(a29);
  a28=(a28+a30);
  a28=sqrt(a28);
  a17=(a17/a28);
  a30=4.0000000000000002e-01;
  a31=(a0+a5);
  a31=(a31-a7);
  a32=casadi_sq(a31);
  a33=(a18+a20);
  a33=(a33-a22);
  a34=casadi_sq(a33);
  a32=(a32+a34);
  a32=sqrt(a32);
  a34=arg[3]? arg[3][2] : 0;
  a35=(a32-a34);
  a35=(a30*a35);
  a35=(a17+a35);
  a36=8.0000000000000004e-01;
  a37=(a0-a7);
  a38=(a37*a2);
  a39=cos(a3);
  a40=(a38*a39);
  a41=(a18-a22);
  a42=(a41*a2);
  a43=sin(a3);
  a44=(a42*a43);
  a40=(a40+a44);
  a44=(a0-a7);
  a45=casadi_sq(a44);
  a46=(a18-a22);
  a47=casadi_sq(a46);
  a45=(a45+a47);
  a45=sqrt(a45);
  a40=(a40/a45);
  a7=(a0-a7);
  a47=casadi_sq(a7);
  a22=(a18-a22);
  a48=casadi_sq(a22);
  a47=(a47+a48);
  a47=sqrt(a47);
  a34=(a47-a34);
  a34=(a30*a34);
  a34=(a40+a34);
  a34=(a36*a34);
  a35=(a35-a34);
  if (res[0]!=0) res[0][0]=a35;
  a35=(a0+a5);
  a34=arg[3]? arg[3][3] : 0;
  a35=(a35-a34);
  a48=(a2+a8);
  a49=(a35*a48);
  a50=(a3+a14);
  a51=cos(a50);
  a52=(a49*a51);
  a53=(a18+a20);
  a54=arg[3]? arg[3][4] : 0;
  a53=(a53-a54);
  a55=(a2+a8);
  a56=(a53*a55);
  a57=(a3+a14);
  a58=sin(a57);
  a59=(a56*a58);
  a52=(a52+a59);
  a59=(a0+a5);
  a59=(a59-a34);
  a60=casadi_sq(a59);
  a61=(a18+a20);
  a61=(a61-a54);
  a62=casadi_sq(a61);
  a60=(a60+a62);
  a60=sqrt(a60);
  a52=(a52/a60);
  a62=(a0+a5);
  a62=(a62-a34);
  a63=casadi_sq(a62);
  a64=(a18+a20);
  a64=(a64-a54);
  a65=casadi_sq(a64);
  a63=(a63+a65);
  a63=sqrt(a63);
  a65=arg[3]? arg[3][5] : 0;
  a66=(a63-a65);
  a66=(a30*a66);
  a66=(a52+a66);
  a67=(a0-a34);
  a68=(a67*a2);
  a69=cos(a3);
  a70=(a68*a69);
  a71=(a18-a54);
  a72=(a71*a2);
  a73=sin(a3);
  a74=(a72*a73);
  a70=(a70+a74);
  a74=(a0-a34);
  a75=casadi_sq(a74);
  a76=(a18-a54);
  a77=casadi_sq(a76);
  a75=(a75+a77);
  a75=sqrt(a75);
  a70=(a70/a75);
  a34=(a0-a34);
  a77=casadi_sq(a34);
  a54=(a18-a54);
  a78=casadi_sq(a54);
  a77=(a77+a78);
  a77=sqrt(a77);
  a65=(a77-a65);
  a65=(a30*a65);
  a65=(a70+a65);
  a65=(a36*a65);
  a66=(a66-a65);
  if (res[0]!=0) res[0][1]=a66;
  a66=(a0+a5);
  a65=arg[3]? arg[3][6] : 0;
  a66=(a66-a65);
  a78=(a2+a8);
  a79=(a66*a78);
  a80=(a3+a14);
  a81=cos(a80);
  a82=(a79*a81);
  a83=(a18+a20);
  a84=arg[3]? arg[3][7] : 0;
  a83=(a83-a84);
  a85=(a2+a8);
  a86=(a83*a85);
  a87=(a3+a14);
  a88=sin(a87);
  a89=(a86*a88);
  a82=(a82+a89);
  a89=(a0+a5);
  a89=(a89-a65);
  a90=casadi_sq(a89);
  a91=(a18+a20);
  a91=(a91-a84);
  a92=casadi_sq(a91);
  a90=(a90+a92);
  a90=sqrt(a90);
  a82=(a82/a90);
  a92=(a0+a5);
  a92=(a92-a65);
  a93=casadi_sq(a92);
  a94=(a18+a20);
  a94=(a94-a84);
  a95=casadi_sq(a94);
  a93=(a93+a95);
  a93=sqrt(a93);
  a95=arg[3]? arg[3][8] : 0;
  a96=(a93-a95);
  a96=(a30*a96);
  a96=(a82+a96);
  a97=(a0-a65);
  a98=(a97*a2);
  a99=cos(a3);
  a100=(a98*a99);
  a101=(a18-a84);
  a102=(a101*a2);
  a103=sin(a3);
  a104=(a102*a103);
  a100=(a100+a104);
  a104=(a0-a65);
  a105=casadi_sq(a104);
  a106=(a18-a84);
  a107=casadi_sq(a106);
  a105=(a105+a107);
  a105=sqrt(a105);
  a100=(a100/a105);
  a65=(a0-a65);
  a107=casadi_sq(a65);
  a84=(a18-a84);
  a108=casadi_sq(a84);
  a107=(a107+a108);
  a107=sqrt(a107);
  a95=(a107-a95);
  a95=(a30*a95);
  a95=(a100+a95);
  a95=(a36*a95);
  a96=(a96-a95);
  if (res[0]!=0) res[0][2]=a96;
  a96=(a0+a5);
  a95=arg[3]? arg[3][9] : 0;
  a96=(a96-a95);
  a108=(a2+a8);
  a109=(a96*a108);
  a110=(a3+a14);
  a111=cos(a110);
  a112=(a109*a111);
  a113=(a18+a20);
  a114=arg[3]? arg[3][10] : 0;
  a113=(a113-a114);
  a115=(a2+a8);
  a116=(a113*a115);
  a117=(a3+a14);
  a118=sin(a117);
  a119=(a116*a118);
  a112=(a112+a119);
  a119=(a0+a5);
  a119=(a119-a95);
  a120=casadi_sq(a119);
  a121=(a18+a20);
  a121=(a121-a114);
  a122=casadi_sq(a121);
  a120=(a120+a122);
  a120=sqrt(a120);
  a112=(a112/a120);
  a122=(a0+a5);
  a122=(a122-a95);
  a123=casadi_sq(a122);
  a124=(a18+a20);
  a124=(a124-a114);
  a125=casadi_sq(a124);
  a123=(a123+a125);
  a123=sqrt(a123);
  a125=arg[3]? arg[3][11] : 0;
  a126=(a123-a125);
  a126=(a30*a126);
  a126=(a112+a126);
  a127=(a0-a95);
  a128=(a127*a2);
  a129=cos(a3);
  a130=(a128*a129);
  a131=(a18-a114);
  a132=(a131*a2);
  a133=sin(a3);
  a134=(a132*a133);
  a130=(a130+a134);
  a134=(a0-a95);
  a135=casadi_sq(a134);
  a136=(a18-a114);
  a137=casadi_sq(a136);
  a135=(a135+a137);
  a135=sqrt(a135);
  a130=(a130/a135);
  a95=(a0-a95);
  a137=casadi_sq(a95);
  a114=(a18-a114);
  a138=casadi_sq(a114);
  a137=(a137+a138);
  a137=sqrt(a137);
  a125=(a137-a125);
  a125=(a30*a125);
  a125=(a130+a125);
  a125=(a36*a125);
  a126=(a126-a125);
  if (res[0]!=0) res[0][3]=a126;
  a126=(a0+a5);
  a125=arg[3]? arg[3][12] : 0;
  a126=(a126-a125);
  a138=(a2+a8);
  a139=(a126*a138);
  a140=(a3+a14);
  a141=cos(a140);
  a142=(a139*a141);
  a143=(a18+a20);
  a144=arg[3]? arg[3][13] : 0;
  a143=(a143-a144);
  a8=(a2+a8);
  a145=(a143*a8);
  a14=(a3+a14);
  a146=sin(a14);
  a147=(a145*a146);
  a142=(a142+a147);
  a147=(a0+a5);
  a147=(a147-a125);
  a148=casadi_sq(a147);
  a149=(a18+a20);
  a149=(a149-a144);
  a150=casadi_sq(a149);
  a148=(a148+a150);
  a148=sqrt(a148);
  a142=(a142/a148);
  a5=(a0+a5);
  a5=(a5-a125);
  a150=casadi_sq(a5);
  a20=(a18+a20);
  a20=(a20-a144);
  a151=casadi_sq(a20);
  a150=(a150+a151);
  a150=sqrt(a150);
  a151=arg[3]? arg[3][14] : 0;
  a152=(a150-a151);
  a152=(a30*a152);
  a152=(a142+a152);
  a153=(a0-a125);
  a154=(a153*a2);
  a155=cos(a3);
  a156=(a154*a155);
  a157=(a18-a144);
  a158=(a157*a2);
  a159=sin(a3);
  a160=(a158*a159);
  a156=(a156+a160);
  a160=(a0-a125);
  a161=casadi_sq(a160);
  a162=(a18-a144);
  a163=casadi_sq(a162);
  a161=(a161+a163);
  a161=sqrt(a161);
  a156=(a156/a161);
  a0=(a0-a125);
  a125=casadi_sq(a0);
  a18=(a18-a144);
  a144=casadi_sq(a18);
  a125=(a125+a144);
  a125=sqrt(a125);
  a151=(a125-a151);
  a151=(a30*a151);
  a151=(a156+a151);
  a151=(a36*a151);
  a152=(a152-a151);
  if (res[0]!=0) res[0][4]=a152;
  a152=(a16*a12);
  a152=(a152/a28);
  a17=(a17/a28);
  a151=(a27/a28);
  a151=(a17*a151);
  a152=(a152-a151);
  a151=(a31/a32);
  a151=(a30*a151);
  a152=(a152+a151);
  a151=(a39*a2);
  a151=(a151/a45);
  a40=(a40/a45);
  a44=(a44/a45);
  a44=(a40*a44);
  a151=(a151-a44);
  a7=(a7/a47);
  a7=(a30*a7);
  a151=(a151+a7);
  a151=(a36*a151);
  a152=(a152-a151);
  if (res[1]!=0) res[1][0]=a152;
  a152=(a26*a23);
  a152=(a152/a28);
  a151=(a29/a28);
  a151=(a17*a151);
  a152=(a152-a151);
  a151=(a33/a32);
  a151=(a30*a151);
  a152=(a152+a151);
  a151=(a43*a2);
  a151=(a151/a45);
  a46=(a46/a45);
  a40=(a40*a46);
  a151=(a151-a40);
  a22=(a22/a47);
  a22=(a30*a22);
  a151=(a151+a22);
  a151=(a36*a151);
  a152=(a152-a151);
  if (res[1]!=0) res[1][1]=a152;
  a152=cos(a3);
  a152=(a2*a152);
  a152=(a1*a152);
  a151=(a23*a152);
  a151=(a26*a151);
  a25=cos(a25);
  a22=(a24*a25);
  a151=(a151+a22);
  a22=sin(a3);
  a22=(a2*a22);
  a22=(a1*a22);
  a47=(a12*a22);
  a47=(a16*a47);
  a15=sin(a15);
  a40=(a13*a15);
  a47=(a47+a40);
  a151=(a151-a47);
  a151=(a151/a28);
  a29=(a29+a29);
  a47=(a29*a152);
  a27=(a27+a27);
  a40=(a27*a22);
  a47=(a47-a40);
  a40=(a28+a28);
  a47=(a47/a40);
  a47=(a17*a47);
  a151=(a151-a47);
  a33=(a33+a33);
  a47=(a33*a152);
  a31=(a31+a31);
  a46=(a31*a22);
  a47=(a47-a46);
  a32=(a32+a32);
  a47=(a47/a32);
  a47=(a30*a47);
  a151=(a151+a47);
  a47=cos(a3);
  a42=(a42*a47);
  a47=sin(a3);
  a38=(a38*a47);
  a42=(a42-a38);
  a42=(a42/a45);
  a42=(a36*a42);
  a151=(a151-a42);
  if (res[1]!=0) res[1][2]=a151;
  a4=(a1*a4);
  a12=(a12*a4);
  a151=1.;
  a42=2.7777777777777776e-02;
  a11=(a2/a11);
  a10=(a10*a11);
  a10=(a2*a10);
  a10=(a10+a9);
  a42=(a42*a10);
  a42=(a1*a42);
  a10=(a151-a42);
  a10=(a6*a10);
  a12=(a12+a10);
  a12=(a16*a12);
  a19=(a1*a19);
  a23=(a23*a19);
  a10=(a151-a42);
  a10=(a21*a10);
  a23=(a23+a10);
  a23=(a26*a23);
  a12=(a12+a23);
  a12=(a12/a28);
  a27=(a27*a4);
  a29=(a29*a19);
  a27=(a27+a29);
  a27=(a27/a40);
  a17=(a17*a27);
  a12=(a12-a17);
  a31=(a31*a4);
  a33=(a33*a19);
  a31=(a31+a33);
  a31=(a31/a32);
  a31=(a30*a31);
  a12=(a12+a31);
  a39=(a39*a37);
  a43=(a43*a41);
  a39=(a39+a43);
  a39=(a39/a45);
  a39=(a36*a39);
  a12=(a12-a39);
  if (res[1]!=0) res[1][3]=a12;
  a25=(a1*a25);
  a24=(a24*a25);
  a15=(a1*a15);
  a13=(a13*a15);
  a24=(a24-a13);
  a24=(a24/a28);
  if (res[1]!=0) res[1][4]=a24;
  a24=5.5555555555555558e-03;
  a13=(a24*a6);
  a13=(a16*a13);
  a15=(a24*a21);
  a15=(a26*a15);
  a13=(a13+a15);
  a13=(a13/a28);
  if (res[1]!=0) res[1][5]=a13;
  a6=(a24*a6);
  a16=(a16*a6);
  a21=(a24*a21);
  a26=(a26*a21);
  a16=(a16+a26);
  a16=(a16/a28);
  if (res[1]!=0) res[1][6]=a16;
  a16=(a51*a48);
  a16=(a16/a60);
  a52=(a52/a60);
  a28=(a59/a60);
  a28=(a52*a28);
  a16=(a16-a28);
  a28=(a62/a63);
  a28=(a30*a28);
  a16=(a16+a28);
  a28=(a69*a2);
  a28=(a28/a75);
  a70=(a70/a75);
  a74=(a74/a75);
  a74=(a70*a74);
  a28=(a28-a74);
  a34=(a34/a77);
  a34=(a30*a34);
  a28=(a28+a34);
  a28=(a36*a28);
  a16=(a16-a28);
  if (res[1]!=0) res[1][7]=a16;
  a16=(a58*a55);
  a16=(a16/a60);
  a28=(a61/a60);
  a28=(a52*a28);
  a16=(a16-a28);
  a28=(a64/a63);
  a28=(a30*a28);
  a16=(a16+a28);
  a28=(a73*a2);
  a28=(a28/a75);
  a76=(a76/a75);
  a70=(a70*a76);
  a28=(a28-a70);
  a54=(a54/a77);
  a54=(a30*a54);
  a28=(a28+a54);
  a28=(a36*a28);
  a16=(a16-a28);
  if (res[1]!=0) res[1][8]=a16;
  a16=(a55*a152);
  a16=(a58*a16);
  a57=cos(a57);
  a28=(a56*a57);
  a16=(a16+a28);
  a28=(a48*a22);
  a28=(a51*a28);
  a50=sin(a50);
  a54=(a49*a50);
  a28=(a28+a54);
  a16=(a16-a28);
  a16=(a16/a60);
  a61=(a61+a61);
  a28=(a61*a152);
  a59=(a59+a59);
  a54=(a59*a22);
  a28=(a28-a54);
  a54=(a60+a60);
  a28=(a28/a54);
  a28=(a52*a28);
  a16=(a16-a28);
  a64=(a64+a64);
  a28=(a64*a152);
  a62=(a62+a62);
  a77=(a62*a22);
  a28=(a28-a77);
  a63=(a63+a63);
  a28=(a28/a63);
  a28=(a30*a28);
  a16=(a16+a28);
  a28=cos(a3);
  a72=(a72*a28);
  a28=sin(a3);
  a68=(a68*a28);
  a72=(a72-a68);
  a72=(a72/a75);
  a72=(a36*a72);
  a16=(a16-a72);
  if (res[1]!=0) res[1][9]=a16;
  a48=(a48*a4);
  a16=(a151-a42);
  a16=(a35*a16);
  a48=(a48+a16);
  a48=(a51*a48);
  a55=(a55*a19);
  a16=(a151-a42);
  a16=(a53*a16);
  a55=(a55+a16);
  a55=(a58*a55);
  a48=(a48+a55);
  a48=(a48/a60);
  a59=(a59*a4);
  a61=(a61*a19);
  a59=(a59+a61);
  a59=(a59/a54);
  a52=(a52*a59);
  a48=(a48-a52);
  a62=(a62*a4);
  a64=(a64*a19);
  a62=(a62+a64);
  a62=(a62/a63);
  a62=(a30*a62);
  a48=(a48+a62);
  a69=(a69*a67);
  a73=(a73*a71);
  a69=(a69+a73);
  a69=(a69/a75);
  a69=(a36*a69);
  a48=(a48-a69);
  if (res[1]!=0) res[1][10]=a48;
  a57=(a1*a57);
  a56=(a56*a57);
  a50=(a1*a50);
  a49=(a49*a50);
  a56=(a56-a49);
  a56=(a56/a60);
  if (res[1]!=0) res[1][11]=a56;
  a56=(a24*a35);
  a56=(a51*a56);
  a49=(a24*a53);
  a49=(a58*a49);
  a56=(a56+a49);
  a56=(a56/a60);
  if (res[1]!=0) res[1][12]=a56;
  a35=(a24*a35);
  a51=(a51*a35);
  a53=(a24*a53);
  a58=(a58*a53);
  a51=(a51+a58);
  a51=(a51/a60);
  if (res[1]!=0) res[1][13]=a51;
  a51=(a81*a78);
  a51=(a51/a90);
  a82=(a82/a90);
  a60=(a89/a90);
  a60=(a82*a60);
  a51=(a51-a60);
  a60=(a92/a93);
  a60=(a30*a60);
  a51=(a51+a60);
  a60=(a99*a2);
  a60=(a60/a105);
  a100=(a100/a105);
  a104=(a104/a105);
  a104=(a100*a104);
  a60=(a60-a104);
  a65=(a65/a107);
  a65=(a30*a65);
  a60=(a60+a65);
  a60=(a36*a60);
  a51=(a51-a60);
  if (res[1]!=0) res[1][14]=a51;
  a51=(a88*a85);
  a51=(a51/a90);
  a60=(a91/a90);
  a60=(a82*a60);
  a51=(a51-a60);
  a60=(a94/a93);
  a60=(a30*a60);
  a51=(a51+a60);
  a60=(a103*a2);
  a60=(a60/a105);
  a106=(a106/a105);
  a100=(a100*a106);
  a60=(a60-a100);
  a84=(a84/a107);
  a84=(a30*a84);
  a60=(a60+a84);
  a60=(a36*a60);
  a51=(a51-a60);
  if (res[1]!=0) res[1][15]=a51;
  a51=(a85*a152);
  a51=(a88*a51);
  a87=cos(a87);
  a60=(a86*a87);
  a51=(a51+a60);
  a60=(a78*a22);
  a60=(a81*a60);
  a80=sin(a80);
  a84=(a79*a80);
  a60=(a60+a84);
  a51=(a51-a60);
  a51=(a51/a90);
  a91=(a91+a91);
  a60=(a91*a152);
  a89=(a89+a89);
  a84=(a89*a22);
  a60=(a60-a84);
  a84=(a90+a90);
  a60=(a60/a84);
  a60=(a82*a60);
  a51=(a51-a60);
  a94=(a94+a94);
  a60=(a94*a152);
  a92=(a92+a92);
  a107=(a92*a22);
  a60=(a60-a107);
  a93=(a93+a93);
  a60=(a60/a93);
  a60=(a30*a60);
  a51=(a51+a60);
  a60=cos(a3);
  a102=(a102*a60);
  a60=sin(a3);
  a98=(a98*a60);
  a102=(a102-a98);
  a102=(a102/a105);
  a102=(a36*a102);
  a51=(a51-a102);
  if (res[1]!=0) res[1][16]=a51;
  a78=(a78*a4);
  a51=(a151-a42);
  a51=(a66*a51);
  a78=(a78+a51);
  a78=(a81*a78);
  a85=(a85*a19);
  a51=(a151-a42);
  a51=(a83*a51);
  a85=(a85+a51);
  a85=(a88*a85);
  a78=(a78+a85);
  a78=(a78/a90);
  a89=(a89*a4);
  a91=(a91*a19);
  a89=(a89+a91);
  a89=(a89/a84);
  a82=(a82*a89);
  a78=(a78-a82);
  a92=(a92*a4);
  a94=(a94*a19);
  a92=(a92+a94);
  a92=(a92/a93);
  a92=(a30*a92);
  a78=(a78+a92);
  a99=(a99*a97);
  a103=(a103*a101);
  a99=(a99+a103);
  a99=(a99/a105);
  a99=(a36*a99);
  a78=(a78-a99);
  if (res[1]!=0) res[1][17]=a78;
  a87=(a1*a87);
  a86=(a86*a87);
  a80=(a1*a80);
  a79=(a79*a80);
  a86=(a86-a79);
  a86=(a86/a90);
  if (res[1]!=0) res[1][18]=a86;
  a86=(a24*a66);
  a86=(a81*a86);
  a79=(a24*a83);
  a79=(a88*a79);
  a86=(a86+a79);
  a86=(a86/a90);
  if (res[1]!=0) res[1][19]=a86;
  a66=(a24*a66);
  a81=(a81*a66);
  a83=(a24*a83);
  a88=(a88*a83);
  a81=(a81+a88);
  a81=(a81/a90);
  if (res[1]!=0) res[1][20]=a81;
  a81=(a111*a108);
  a81=(a81/a120);
  a112=(a112/a120);
  a90=(a119/a120);
  a90=(a112*a90);
  a81=(a81-a90);
  a90=(a122/a123);
  a90=(a30*a90);
  a81=(a81+a90);
  a90=(a129*a2);
  a90=(a90/a135);
  a130=(a130/a135);
  a134=(a134/a135);
  a134=(a130*a134);
  a90=(a90-a134);
  a95=(a95/a137);
  a95=(a30*a95);
  a90=(a90+a95);
  a90=(a36*a90);
  a81=(a81-a90);
  if (res[1]!=0) res[1][21]=a81;
  a81=(a118*a115);
  a81=(a81/a120);
  a90=(a121/a120);
  a90=(a112*a90);
  a81=(a81-a90);
  a90=(a124/a123);
  a90=(a30*a90);
  a81=(a81+a90);
  a90=(a133*a2);
  a90=(a90/a135);
  a136=(a136/a135);
  a130=(a130*a136);
  a90=(a90-a130);
  a114=(a114/a137);
  a114=(a30*a114);
  a90=(a90+a114);
  a90=(a36*a90);
  a81=(a81-a90);
  if (res[1]!=0) res[1][22]=a81;
  a81=(a115*a152);
  a81=(a118*a81);
  a117=cos(a117);
  a90=(a116*a117);
  a81=(a81+a90);
  a90=(a108*a22);
  a90=(a111*a90);
  a110=sin(a110);
  a114=(a109*a110);
  a90=(a90+a114);
  a81=(a81-a90);
  a81=(a81/a120);
  a121=(a121+a121);
  a90=(a121*a152);
  a119=(a119+a119);
  a114=(a119*a22);
  a90=(a90-a114);
  a114=(a120+a120);
  a90=(a90/a114);
  a90=(a112*a90);
  a81=(a81-a90);
  a124=(a124+a124);
  a90=(a124*a152);
  a122=(a122+a122);
  a137=(a122*a22);
  a90=(a90-a137);
  a123=(a123+a123);
  a90=(a90/a123);
  a90=(a30*a90);
  a81=(a81+a90);
  a90=cos(a3);
  a132=(a132*a90);
  a90=sin(a3);
  a128=(a128*a90);
  a132=(a132-a128);
  a132=(a132/a135);
  a132=(a36*a132);
  a81=(a81-a132);
  if (res[1]!=0) res[1][23]=a81;
  a108=(a108*a4);
  a81=(a151-a42);
  a81=(a96*a81);
  a108=(a108+a81);
  a108=(a111*a108);
  a115=(a115*a19);
  a81=(a151-a42);
  a81=(a113*a81);
  a115=(a115+a81);
  a115=(a118*a115);
  a108=(a108+a115);
  a108=(a108/a120);
  a119=(a119*a4);
  a121=(a121*a19);
  a119=(a119+a121);
  a119=(a119/a114);
  a112=(a112*a119);
  a108=(a108-a112);
  a122=(a122*a4);
  a124=(a124*a19);
  a122=(a122+a124);
  a122=(a122/a123);
  a122=(a30*a122);
  a108=(a108+a122);
  a129=(a129*a127);
  a133=(a133*a131);
  a129=(a129+a133);
  a129=(a129/a135);
  a129=(a36*a129);
  a108=(a108-a129);
  if (res[1]!=0) res[1][24]=a108;
  a117=(a1*a117);
  a116=(a116*a117);
  a110=(a1*a110);
  a109=(a109*a110);
  a116=(a116-a109);
  a116=(a116/a120);
  if (res[1]!=0) res[1][25]=a116;
  a116=(a24*a96);
  a116=(a111*a116);
  a109=(a24*a113);
  a109=(a118*a109);
  a116=(a116+a109);
  a116=(a116/a120);
  if (res[1]!=0) res[1][26]=a116;
  a96=(a24*a96);
  a111=(a111*a96);
  a113=(a24*a113);
  a118=(a118*a113);
  a111=(a111+a118);
  a111=(a111/a120);
  if (res[1]!=0) res[1][27]=a111;
  a111=(a141*a138);
  a111=(a111/a148);
  a142=(a142/a148);
  a120=(a147/a148);
  a120=(a142*a120);
  a111=(a111-a120);
  a120=(a5/a150);
  a120=(a30*a120);
  a111=(a111+a120);
  a120=(a155*a2);
  a120=(a120/a161);
  a156=(a156/a161);
  a160=(a160/a161);
  a160=(a156*a160);
  a120=(a120-a160);
  a0=(a0/a125);
  a0=(a30*a0);
  a120=(a120+a0);
  a120=(a36*a120);
  a111=(a111-a120);
  if (res[1]!=0) res[1][28]=a111;
  a111=(a146*a8);
  a111=(a111/a148);
  a120=(a149/a148);
  a120=(a142*a120);
  a111=(a111-a120);
  a120=(a20/a150);
  a120=(a30*a120);
  a111=(a111+a120);
  a2=(a159*a2);
  a2=(a2/a161);
  a162=(a162/a161);
  a156=(a156*a162);
  a2=(a2-a156);
  a18=(a18/a125);
  a18=(a30*a18);
  a2=(a2+a18);
  a2=(a36*a2);
  a111=(a111-a2);
  if (res[1]!=0) res[1][29]=a111;
  a111=(a8*a152);
  a111=(a146*a111);
  a14=cos(a14);
  a2=(a145*a14);
  a111=(a111+a2);
  a2=(a138*a22);
  a2=(a141*a2);
  a140=sin(a140);
  a18=(a139*a140);
  a2=(a2+a18);
  a111=(a111-a2);
  a111=(a111/a148);
  a149=(a149+a149);
  a2=(a149*a152);
  a147=(a147+a147);
  a18=(a147*a22);
  a2=(a2-a18);
  a18=(a148+a148);
  a2=(a2/a18);
  a2=(a142*a2);
  a111=(a111-a2);
  a20=(a20+a20);
  a152=(a20*a152);
  a5=(a5+a5);
  a22=(a5*a22);
  a152=(a152-a22);
  a150=(a150+a150);
  a152=(a152/a150);
  a152=(a30*a152);
  a111=(a111+a152);
  a152=cos(a3);
  a158=(a158*a152);
  a3=sin(a3);
  a154=(a154*a3);
  a158=(a158-a154);
  a158=(a158/a161);
  a158=(a36*a158);
  a111=(a111-a158);
  if (res[1]!=0) res[1][30]=a111;
  a138=(a138*a4);
  a111=(a151-a42);
  a111=(a126*a111);
  a138=(a138+a111);
  a138=(a141*a138);
  a8=(a8*a19);
  a151=(a151-a42);
  a151=(a143*a151);
  a8=(a8+a151);
  a8=(a146*a8);
  a138=(a138+a8);
  a138=(a138/a148);
  a147=(a147*a4);
  a149=(a149*a19);
  a147=(a147+a149);
  a147=(a147/a18);
  a142=(a142*a147);
  a138=(a138-a142);
  a5=(a5*a4);
  a20=(a20*a19);
  a5=(a5+a20);
  a5=(a5/a150);
  a30=(a30*a5);
  a138=(a138+a30);
  a155=(a155*a153);
  a159=(a159*a157);
  a155=(a155+a159);
  a155=(a155/a161);
  a36=(a36*a155);
  a138=(a138-a36);
  if (res[1]!=0) res[1][31]=a138;
  a14=(a1*a14);
  a145=(a145*a14);
  a1=(a1*a140);
  a139=(a139*a1);
  a145=(a145-a139);
  a145=(a145/a148);
  if (res[1]!=0) res[1][32]=a145;
  a145=(a24*a126);
  a145=(a141*a145);
  a139=(a24*a143);
  a139=(a146*a139);
  a145=(a145+a139);
  a145=(a145/a148);
  if (res[1]!=0) res[1][33]=a145;
  a126=(a24*a126);
  a141=(a141*a126);
  a24=(a24*a143);
  a146=(a146*a24);
  a141=(a141+a146);
  a141=(a141/a148);
  if (res[1]!=0) res[1][34]=a141;
  return 0;
}

CASADI_SYMBOL_EXPORT int heron_constr_h_fun_jac_uxt_zt(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int heron_constr_h_fun_jac_uxt_zt_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int heron_constr_h_fun_jac_uxt_zt_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void heron_constr_h_fun_jac_uxt_zt_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int heron_constr_h_fun_jac_uxt_zt_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void heron_constr_h_fun_jac_uxt_zt_release(int mem) {
}

CASADI_SYMBOL_EXPORT void heron_constr_h_fun_jac_uxt_zt_incref(void) {
}

CASADI_SYMBOL_EXPORT void heron_constr_h_fun_jac_uxt_zt_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int heron_constr_h_fun_jac_uxt_zt_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int heron_constr_h_fun_jac_uxt_zt_n_out(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_real heron_constr_h_fun_jac_uxt_zt_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* heron_constr_h_fun_jac_uxt_zt_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* heron_constr_h_fun_jac_uxt_zt_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* heron_constr_h_fun_jac_uxt_zt_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    case 3: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* heron_constr_h_fun_jac_uxt_zt_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s4;
    case 1: return casadi_s5;
    case 2: return casadi_s6;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int heron_constr_h_fun_jac_uxt_zt_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4;
  if (sz_res) *sz_res = 3;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
