/* This file was automatically generated by CasADi 3.6.4.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) heron_constr_h_fun_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[11] = {7, 1, 0, 7, 0, 1, 2, 3, 4, 5, 6};
static const casadi_int casadi_s1[6] = {2, 1, 0, 2, 0, 1};
static const casadi_int casadi_s2[3] = {0, 0, 0};
static const casadi_int casadi_s3[19] = {15, 1, 0, 15, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14};
static const casadi_int casadi_s4[9] = {5, 1, 0, 5, 0, 1, 2, 3, 4};

/* heron_constr_h_fun:(i0[7],i1[2],i2[],i3[15])->(o0[5]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a10, a11, a12, a13, a14, a15, a16, a17, a18, a19, a2, a20, a3, a4, a5, a6, a7, a8, a9;
  a0=arg[3]? arg[3][0] : 0;
  a1=arg[0]? arg[0][0] : 0;
  a2=1.0000000000000001e-01;
  a3=arg[0]? arg[0][3] : 0;
  a4=arg[0]? arg[0][2] : 0;
  a5=cos(a4);
  a5=(a3*a5);
  a5=(a2*a5);
  a5=(a1+a5);
  a6=(a0-a5);
  a7=4.;
  a8=arg[0]? arg[0][5] : 0;
  a9=arg[0]? arg[0][6] : 0;
  a8=(a8+a9);
  a9=10.;
  a10=1.6899999999999999e+01;
  a11=casadi_sq(a3);
  a12=1.0000000000000001e-05;
  a11=(a11+a12);
  a11=sqrt(a11);
  a10=(a10*a11);
  a9=(a9+a10);
  a9=(a9*a3);
  a8=(a8-a9);
  a9=36.;
  a8=(a8/a9);
  a8=(a2*a8);
  a8=(a3+a8);
  a9=5.9999999999999998e-01;
  a10=(a8/a9);
  a10=(a7*a10);
  a11=arg[0]? arg[0][4] : 0;
  a11=(a2*a11);
  a11=(a4+a11);
  a12=1.5707963267948966e+00;
  a13=(a11-a12);
  a13=cos(a13);
  a13=(a10*a13);
  a6=(a6-a13);
  a6=casadi_sq(a6);
  a13=arg[3]? arg[3][1] : 0;
  a14=arg[0]? arg[0][1] : 0;
  a15=sin(a4);
  a15=(a3*a15);
  a2=(a2*a15);
  a2=(a14+a2);
  a15=(a13-a2);
  a16=(a11-a12);
  a16=sin(a16);
  a16=(a10*a16);
  a15=(a15-a16);
  a15=casadi_sq(a15);
  a6=(a6+a15);
  a6=sqrt(a6);
  a15=arg[3]? arg[3][2] : 0;
  a16=(a15+a10);
  a6=(a6-a16);
  a6=exp(a6);
  a16=(a0-a5);
  a17=(a11+a12);
  a17=cos(a17);
  a17=(a10*a17);
  a16=(a16-a17);
  a16=casadi_sq(a16);
  a17=(a13-a2);
  a18=(a11+a12);
  a18=sin(a18);
  a18=(a10*a18);
  a17=(a17-a18);
  a17=casadi_sq(a17);
  a16=(a16+a17);
  a16=sqrt(a16);
  a10=(a15+a10);
  a16=(a16-a10);
  a16=exp(a16);
  a6=(a6+a16);
  a16=1.;
  a6=(a6-a16);
  a6=log(a6);
  a10=9.7499999999999998e-01;
  a17=(a0-a1);
  a18=(a3/a9);
  a18=(a7*a18);
  a19=(a4-a12);
  a19=cos(a19);
  a19=(a18*a19);
  a17=(a17-a19);
  a17=casadi_sq(a17);
  a19=(a13-a14);
  a20=(a4-a12);
  a20=sin(a20);
  a20=(a18*a20);
  a19=(a19-a20);
  a19=casadi_sq(a19);
  a17=(a17+a19);
  a17=sqrt(a17);
  a19=(a15+a18);
  a17=(a17-a19);
  a17=exp(a17);
  a0=(a0-a1);
  a19=(a4+a12);
  a19=cos(a19);
  a19=(a18*a19);
  a0=(a0-a19);
  a0=casadi_sq(a0);
  a13=(a13-a14);
  a19=(a4+a12);
  a19=sin(a19);
  a19=(a18*a19);
  a13=(a13-a19);
  a13=casadi_sq(a13);
  a0=(a0+a13);
  a0=sqrt(a0);
  a15=(a15+a18);
  a0=(a0-a15);
  a0=exp(a0);
  a17=(a17+a0);
  a17=(a17-a16);
  a17=log(a17);
  a17=(a10*a17);
  a6=(a6-a17);
  if (res[0]!=0) res[0][0]=a6;
  a6=arg[3]? arg[3][3] : 0;
  a17=(a6-a5);
  a0=(a8/a9);
  a0=(a7*a0);
  a15=(a11-a12);
  a15=cos(a15);
  a15=(a0*a15);
  a17=(a17-a15);
  a17=casadi_sq(a17);
  a15=arg[3]? arg[3][4] : 0;
  a18=(a15-a2);
  a13=(a11-a12);
  a13=sin(a13);
  a13=(a0*a13);
  a18=(a18-a13);
  a18=casadi_sq(a18);
  a17=(a17+a18);
  a17=sqrt(a17);
  a18=arg[3]? arg[3][5] : 0;
  a13=(a18+a0);
  a17=(a17-a13);
  a17=exp(a17);
  a13=(a6-a5);
  a19=(a11+a12);
  a19=cos(a19);
  a19=(a0*a19);
  a13=(a13-a19);
  a13=casadi_sq(a13);
  a19=(a15-a2);
  a20=(a11+a12);
  a20=sin(a20);
  a20=(a0*a20);
  a19=(a19-a20);
  a19=casadi_sq(a19);
  a13=(a13+a19);
  a13=sqrt(a13);
  a0=(a18+a0);
  a13=(a13-a0);
  a13=exp(a13);
  a17=(a17+a13);
  a17=(a17-a16);
  a17=log(a17);
  a13=(a6-a1);
  a0=(a3/a9);
  a0=(a7*a0);
  a19=(a4-a12);
  a19=cos(a19);
  a19=(a0*a19);
  a13=(a13-a19);
  a13=casadi_sq(a13);
  a19=(a15-a14);
  a20=(a4-a12);
  a20=sin(a20);
  a20=(a0*a20);
  a19=(a19-a20);
  a19=casadi_sq(a19);
  a13=(a13+a19);
  a13=sqrt(a13);
  a19=(a18+a0);
  a13=(a13-a19);
  a13=exp(a13);
  a6=(a6-a1);
  a19=(a4+a12);
  a19=cos(a19);
  a19=(a0*a19);
  a6=(a6-a19);
  a6=casadi_sq(a6);
  a15=(a15-a14);
  a19=(a4+a12);
  a19=sin(a19);
  a19=(a0*a19);
  a15=(a15-a19);
  a15=casadi_sq(a15);
  a6=(a6+a15);
  a6=sqrt(a6);
  a18=(a18+a0);
  a6=(a6-a18);
  a6=exp(a6);
  a13=(a13+a6);
  a13=(a13-a16);
  a13=log(a13);
  a13=(a10*a13);
  a17=(a17-a13);
  if (res[0]!=0) res[0][1]=a17;
  a17=arg[3]? arg[3][6] : 0;
  a13=(a17-a5);
  a6=(a8/a9);
  a6=(a7*a6);
  a18=(a11-a12);
  a18=cos(a18);
  a18=(a6*a18);
  a13=(a13-a18);
  a13=casadi_sq(a13);
  a18=arg[3]? arg[3][7] : 0;
  a0=(a18-a2);
  a15=(a11-a12);
  a15=sin(a15);
  a15=(a6*a15);
  a0=(a0-a15);
  a0=casadi_sq(a0);
  a13=(a13+a0);
  a13=sqrt(a13);
  a0=arg[3]? arg[3][8] : 0;
  a15=(a0+a6);
  a13=(a13-a15);
  a13=exp(a13);
  a15=(a17-a5);
  a19=(a11+a12);
  a19=cos(a19);
  a19=(a6*a19);
  a15=(a15-a19);
  a15=casadi_sq(a15);
  a19=(a18-a2);
  a20=(a11+a12);
  a20=sin(a20);
  a20=(a6*a20);
  a19=(a19-a20);
  a19=casadi_sq(a19);
  a15=(a15+a19);
  a15=sqrt(a15);
  a6=(a0+a6);
  a15=(a15-a6);
  a15=exp(a15);
  a13=(a13+a15);
  a13=(a13-a16);
  a13=log(a13);
  a15=(a17-a1);
  a6=(a3/a9);
  a6=(a7*a6);
  a19=(a4-a12);
  a19=cos(a19);
  a19=(a6*a19);
  a15=(a15-a19);
  a15=casadi_sq(a15);
  a19=(a18-a14);
  a20=(a4-a12);
  a20=sin(a20);
  a20=(a6*a20);
  a19=(a19-a20);
  a19=casadi_sq(a19);
  a15=(a15+a19);
  a15=sqrt(a15);
  a19=(a0+a6);
  a15=(a15-a19);
  a15=exp(a15);
  a17=(a17-a1);
  a19=(a4+a12);
  a19=cos(a19);
  a19=(a6*a19);
  a17=(a17-a19);
  a17=casadi_sq(a17);
  a18=(a18-a14);
  a19=(a4+a12);
  a19=sin(a19);
  a19=(a6*a19);
  a18=(a18-a19);
  a18=casadi_sq(a18);
  a17=(a17+a18);
  a17=sqrt(a17);
  a0=(a0+a6);
  a17=(a17-a0);
  a17=exp(a17);
  a15=(a15+a17);
  a15=(a15-a16);
  a15=log(a15);
  a15=(a10*a15);
  a13=(a13-a15);
  if (res[0]!=0) res[0][2]=a13;
  a13=arg[3]? arg[3][9] : 0;
  a15=(a13-a5);
  a17=(a8/a9);
  a17=(a7*a17);
  a0=(a11-a12);
  a0=cos(a0);
  a0=(a17*a0);
  a15=(a15-a0);
  a15=casadi_sq(a15);
  a0=arg[3]? arg[3][10] : 0;
  a6=(a0-a2);
  a18=(a11-a12);
  a18=sin(a18);
  a18=(a17*a18);
  a6=(a6-a18);
  a6=casadi_sq(a6);
  a15=(a15+a6);
  a15=sqrt(a15);
  a6=arg[3]? arg[3][11] : 0;
  a18=(a6+a17);
  a15=(a15-a18);
  a15=exp(a15);
  a18=(a13-a5);
  a19=(a11+a12);
  a19=cos(a19);
  a19=(a17*a19);
  a18=(a18-a19);
  a18=casadi_sq(a18);
  a19=(a0-a2);
  a20=(a11+a12);
  a20=sin(a20);
  a20=(a17*a20);
  a19=(a19-a20);
  a19=casadi_sq(a19);
  a18=(a18+a19);
  a18=sqrt(a18);
  a17=(a6+a17);
  a18=(a18-a17);
  a18=exp(a18);
  a15=(a15+a18);
  a15=(a15-a16);
  a15=log(a15);
  a18=(a13-a1);
  a17=(a3/a9);
  a17=(a7*a17);
  a19=(a4-a12);
  a19=cos(a19);
  a19=(a17*a19);
  a18=(a18-a19);
  a18=casadi_sq(a18);
  a19=(a0-a14);
  a20=(a4-a12);
  a20=sin(a20);
  a20=(a17*a20);
  a19=(a19-a20);
  a19=casadi_sq(a19);
  a18=(a18+a19);
  a18=sqrt(a18);
  a19=(a6+a17);
  a18=(a18-a19);
  a18=exp(a18);
  a13=(a13-a1);
  a19=(a4+a12);
  a19=cos(a19);
  a19=(a17*a19);
  a13=(a13-a19);
  a13=casadi_sq(a13);
  a0=(a0-a14);
  a19=(a4+a12);
  a19=sin(a19);
  a19=(a17*a19);
  a0=(a0-a19);
  a0=casadi_sq(a0);
  a13=(a13+a0);
  a13=sqrt(a13);
  a6=(a6+a17);
  a13=(a13-a6);
  a13=exp(a13);
  a18=(a18+a13);
  a18=(a18-a16);
  a18=log(a18);
  a18=(a10*a18);
  a15=(a15-a18);
  if (res[0]!=0) res[0][3]=a15;
  a15=arg[3]? arg[3][12] : 0;
  a18=(a15-a5);
  a8=(a8/a9);
  a8=(a7*a8);
  a13=(a11-a12);
  a13=cos(a13);
  a13=(a8*a13);
  a18=(a18-a13);
  a18=casadi_sq(a18);
  a13=arg[3]? arg[3][13] : 0;
  a6=(a13-a2);
  a17=(a11-a12);
  a17=sin(a17);
  a17=(a8*a17);
  a6=(a6-a17);
  a6=casadi_sq(a6);
  a18=(a18+a6);
  a18=sqrt(a18);
  a6=arg[3]? arg[3][14] : 0;
  a17=(a6+a8);
  a18=(a18-a17);
  a18=exp(a18);
  a5=(a15-a5);
  a17=(a11+a12);
  a17=cos(a17);
  a17=(a8*a17);
  a5=(a5-a17);
  a5=casadi_sq(a5);
  a2=(a13-a2);
  a11=(a11+a12);
  a11=sin(a11);
  a11=(a8*a11);
  a2=(a2-a11);
  a2=casadi_sq(a2);
  a5=(a5+a2);
  a5=sqrt(a5);
  a8=(a6+a8);
  a5=(a5-a8);
  a5=exp(a5);
  a18=(a18+a5);
  a18=(a18-a16);
  a18=log(a18);
  a5=(a15-a1);
  a3=(a3/a9);
  a7=(a7*a3);
  a3=(a4-a12);
  a3=cos(a3);
  a3=(a7*a3);
  a5=(a5-a3);
  a5=casadi_sq(a5);
  a3=(a13-a14);
  a9=(a4-a12);
  a9=sin(a9);
  a9=(a7*a9);
  a3=(a3-a9);
  a3=casadi_sq(a3);
  a5=(a5+a3);
  a5=sqrt(a5);
  a3=(a6+a7);
  a5=(a5-a3);
  a5=exp(a5);
  a15=(a15-a1);
  a1=(a4+a12);
  a1=cos(a1);
  a1=(a7*a1);
  a15=(a15-a1);
  a15=casadi_sq(a15);
  a13=(a13-a14);
  a4=(a4+a12);
  a4=sin(a4);
  a4=(a7*a4);
  a13=(a13-a4);
  a13=casadi_sq(a13);
  a15=(a15+a13);
  a15=sqrt(a15);
  a6=(a6+a7);
  a15=(a15-a6);
  a15=exp(a15);
  a5=(a5+a15);
  a5=(a5-a16);
  a5=log(a5);
  a10=(a10*a5);
  a18=(a18-a10);
  if (res[0]!=0) res[0][4]=a18;
  return 0;
}

CASADI_SYMBOL_EXPORT int heron_constr_h_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int heron_constr_h_fun_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int heron_constr_h_fun_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void heron_constr_h_fun_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int heron_constr_h_fun_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void heron_constr_h_fun_release(int mem) {
}

CASADI_SYMBOL_EXPORT void heron_constr_h_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void heron_constr_h_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int heron_constr_h_fun_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int heron_constr_h_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real heron_constr_h_fun_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* heron_constr_h_fun_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* heron_constr_h_fun_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* heron_constr_h_fun_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    case 3: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* heron_constr_h_fun_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s4;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int heron_constr_h_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
