/* This file was automatically generated by CasADi 3.6.3.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) heron_expl_vde_forw_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[11] = {7, 1, 0, 7, 0, 1, 2, 3, 4, 5, 6};
static const casadi_int casadi_s1[59] = {7, 7, 0, 7, 14, 21, 28, 35, 42, 49, 0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6};
static const casadi_int casadi_s2[19] = {7, 2, 0, 7, 14, 0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6};
static const casadi_int casadi_s3[6] = {2, 1, 0, 2, 0, 1};
static const casadi_int casadi_s4[9] = {5, 1, 0, 5, 0, 1, 2, 3, 4};

/* heron_expl_vde_forw:(i0[7],i1[7x7],i2[7x2],i3[2],i4[5])->(o0[7],o1[7x7],o2[7x2]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a10, a11, a12, a13, a14, a15, a16, a17, a18, a19, a2, a20, a21, a22, a23, a24, a25, a26, a27, a3, a4, a5, a6, a7, a8, a9;
  a0=arg[0]? arg[0][3] : 0;
  a1=arg[0]? arg[0][2] : 0;
  a2=cos(a1);
  a3=(a0*a2);
  if (res[0]!=0) res[0][0]=a3;
  a3=sin(a1);
  a4=(a0*a3);
  if (res[0]!=0) res[0][1]=a4;
  a4=arg[0]? arg[0][4] : 0;
  if (res[0]!=0) res[0][2]=a4;
  a5=arg[0]? arg[0][5] : 0;
  a6=arg[0]? arg[0][6] : 0;
  a7=(a5+a6);
  a8=10.;
  a9=1.6899999999999999e+01;
  a10=casadi_sq(a0);
  a11=1.0000000000000001e-05;
  a10=(a10+a11);
  a10=sqrt(a10);
  a12=(a9*a10);
  a8=(a8+a12);
  a12=(a8*a0);
  a7=(a7-a12);
  a12=36.;
  a7=(a7/a12);
  a12=arg[4]? arg[4][3] : 0;
  a7=(a7+a12);
  if (res[0]!=0) res[0][3]=a7;
  a7=7.2999999999999998e-01;
  a6=(a6-a5);
  a6=(a7*a6);
  a5=2.;
  a6=(a6/a5);
  a5=5.;
  a12=13.;
  a13=casadi_sq(a4);
  a13=(a13+a11);
  a13=sqrt(a13);
  a11=(a12*a13);
  a5=(a5+a11);
  a11=(a5*a4);
  a6=(a6-a11);
  a11=8.3499999999999996e+00;
  a6=(a6/a11);
  a11=arg[4]? arg[4][4] : 0;
  a6=(a6+a11);
  if (res[0]!=0) res[0][4]=a6;
  a6=arg[3]? arg[3][0] : 0;
  if (res[0]!=0) res[0][5]=a6;
  a6=arg[3]? arg[3][1] : 0;
  if (res[0]!=0) res[0][6]=a6;
  a6=arg[1]? arg[1][3] : 0;
  a11=(a2*a6);
  a14=sin(a1);
  a15=arg[1]? arg[1][2] : 0;
  a16=(a14*a15);
  a16=(a0*a16);
  a11=(a11-a16);
  if (res[1]!=0) res[1][0]=a11;
  a11=(a3*a6);
  a16=cos(a1);
  a15=(a16*a15);
  a15=(a0*a15);
  a11=(a11+a15);
  if (res[1]!=0) res[1][1]=a11;
  a11=arg[1]? arg[1][4] : 0;
  if (res[1]!=0) res[1][2]=a11;
  a15=2.7777777777777776e-02;
  a17=arg[1]? arg[1][5] : 0;
  a18=arg[1]? arg[1][6] : 0;
  a19=(a17+a18);
  a20=(a0+a0);
  a21=(a20*a6);
  a22=(a10+a10);
  a21=(a21/a22);
  a21=(a9*a21);
  a21=(a0*a21);
  a6=(a8*a6);
  a21=(a21+a6);
  a19=(a19-a21);
  a19=(a15*a19);
  if (res[1]!=0) res[1][3]=a19;
  a19=1.1976047904191617e-01;
  a21=5.0000000000000000e-01;
  a18=(a18-a17);
  a18=(a7*a18);
  a18=(a21*a18);
  a17=(a4+a4);
  a6=(a17*a11);
  a23=(a13+a13);
  a6=(a6/a23);
  a6=(a12*a6);
  a6=(a4*a6);
  a11=(a5*a11);
  a6=(a6+a11);
  a18=(a18-a6);
  a18=(a19*a18);
  if (res[1]!=0) res[1][4]=a18;
  a18=0.;
  if (res[1]!=0) res[1][5]=a18;
  if (res[1]!=0) res[1][6]=a18;
  a6=arg[1]? arg[1][10] : 0;
  a11=(a2*a6);
  a24=arg[1]? arg[1][9] : 0;
  a25=(a14*a24);
  a25=(a0*a25);
  a11=(a11-a25);
  if (res[1]!=0) res[1][7]=a11;
  a11=(a3*a6);
  a24=(a16*a24);
  a24=(a0*a24);
  a11=(a11+a24);
  if (res[1]!=0) res[1][8]=a11;
  a11=arg[1]? arg[1][11] : 0;
  if (res[1]!=0) res[1][9]=a11;
  a24=arg[1]? arg[1][12] : 0;
  a25=arg[1]? arg[1][13] : 0;
  a26=(a24+a25);
  a27=(a20*a6);
  a27=(a27/a22);
  a27=(a9*a27);
  a27=(a0*a27);
  a6=(a8*a6);
  a27=(a27+a6);
  a26=(a26-a27);
  a26=(a15*a26);
  if (res[1]!=0) res[1][10]=a26;
  a25=(a25-a24);
  a25=(a7*a25);
  a25=(a21*a25);
  a24=(a17*a11);
  a24=(a24/a23);
  a24=(a12*a24);
  a24=(a4*a24);
  a11=(a5*a11);
  a24=(a24+a11);
  a25=(a25-a24);
  a25=(a19*a25);
  if (res[1]!=0) res[1][11]=a25;
  if (res[1]!=0) res[1][12]=a18;
  if (res[1]!=0) res[1][13]=a18;
  a25=arg[1]? arg[1][17] : 0;
  a24=(a2*a25);
  a11=arg[1]? arg[1][16] : 0;
  a26=(a14*a11);
  a26=(a0*a26);
  a24=(a24-a26);
  if (res[1]!=0) res[1][14]=a24;
  a24=(a3*a25);
  a11=(a16*a11);
  a11=(a0*a11);
  a24=(a24+a11);
  if (res[1]!=0) res[1][15]=a24;
  a24=arg[1]? arg[1][18] : 0;
  if (res[1]!=0) res[1][16]=a24;
  a11=arg[1]? arg[1][19] : 0;
  a26=arg[1]? arg[1][20] : 0;
  a27=(a11+a26);
  a6=(a20*a25);
  a6=(a6/a22);
  a6=(a9*a6);
  a6=(a0*a6);
  a25=(a8*a25);
  a6=(a6+a25);
  a27=(a27-a6);
  a27=(a15*a27);
  if (res[1]!=0) res[1][17]=a27;
  a26=(a26-a11);
  a26=(a7*a26);
  a26=(a21*a26);
  a11=(a17*a24);
  a11=(a11/a23);
  a11=(a12*a11);
  a11=(a4*a11);
  a24=(a5*a24);
  a11=(a11+a24);
  a26=(a26-a11);
  a26=(a19*a26);
  if (res[1]!=0) res[1][18]=a26;
  if (res[1]!=0) res[1][19]=a18;
  if (res[1]!=0) res[1][20]=a18;
  a26=arg[1]? arg[1][24] : 0;
  a11=(a2*a26);
  a24=arg[1]? arg[1][23] : 0;
  a27=(a14*a24);
  a27=(a0*a27);
  a11=(a11-a27);
  if (res[1]!=0) res[1][21]=a11;
  a11=(a3*a26);
  a24=(a16*a24);
  a24=(a0*a24);
  a11=(a11+a24);
  if (res[1]!=0) res[1][22]=a11;
  a11=arg[1]? arg[1][25] : 0;
  if (res[1]!=0) res[1][23]=a11;
  a24=arg[1]? arg[1][26] : 0;
  a27=arg[1]? arg[1][27] : 0;
  a6=(a24+a27);
  a25=(a20*a26);
  a25=(a25/a22);
  a25=(a9*a25);
  a25=(a0*a25);
  a26=(a8*a26);
  a25=(a25+a26);
  a6=(a6-a25);
  a6=(a15*a6);
  if (res[1]!=0) res[1][24]=a6;
  a27=(a27-a24);
  a27=(a7*a27);
  a27=(a21*a27);
  a24=(a17*a11);
  a24=(a24/a23);
  a24=(a12*a24);
  a24=(a4*a24);
  a11=(a5*a11);
  a24=(a24+a11);
  a27=(a27-a24);
  a27=(a19*a27);
  if (res[1]!=0) res[1][25]=a27;
  if (res[1]!=0) res[1][26]=a18;
  if (res[1]!=0) res[1][27]=a18;
  a27=arg[1]? arg[1][31] : 0;
  a24=(a2*a27);
  a11=arg[1]? arg[1][30] : 0;
  a6=(a14*a11);
  a6=(a0*a6);
  a24=(a24-a6);
  if (res[1]!=0) res[1][28]=a24;
  a24=(a3*a27);
  a11=(a16*a11);
  a11=(a0*a11);
  a24=(a24+a11);
  if (res[1]!=0) res[1][29]=a24;
  a24=arg[1]? arg[1][32] : 0;
  if (res[1]!=0) res[1][30]=a24;
  a11=arg[1]? arg[1][33] : 0;
  a6=arg[1]? arg[1][34] : 0;
  a25=(a11+a6);
  a26=(a20*a27);
  a26=(a26/a22);
  a26=(a9*a26);
  a26=(a0*a26);
  a27=(a8*a27);
  a26=(a26+a27);
  a25=(a25-a26);
  a25=(a15*a25);
  if (res[1]!=0) res[1][31]=a25;
  a6=(a6-a11);
  a6=(a7*a6);
  a6=(a21*a6);
  a11=(a17*a24);
  a11=(a11/a23);
  a11=(a12*a11);
  a11=(a4*a11);
  a24=(a5*a24);
  a11=(a11+a24);
  a6=(a6-a11);
  a6=(a19*a6);
  if (res[1]!=0) res[1][32]=a6;
  if (res[1]!=0) res[1][33]=a18;
  if (res[1]!=0) res[1][34]=a18;
  a6=arg[1]? arg[1][38] : 0;
  a11=(a2*a6);
  a24=arg[1]? arg[1][37] : 0;
  a25=(a14*a24);
  a25=(a0*a25);
  a11=(a11-a25);
  if (res[1]!=0) res[1][35]=a11;
  a11=(a3*a6);
  a24=(a16*a24);
  a24=(a0*a24);
  a11=(a11+a24);
  if (res[1]!=0) res[1][36]=a11;
  a11=arg[1]? arg[1][39] : 0;
  if (res[1]!=0) res[1][37]=a11;
  a24=arg[1]? arg[1][40] : 0;
  a25=arg[1]? arg[1][41] : 0;
  a26=(a24+a25);
  a27=(a20*a6);
  a27=(a27/a22);
  a27=(a9*a27);
  a27=(a0*a27);
  a6=(a8*a6);
  a27=(a27+a6);
  a26=(a26-a27);
  a26=(a15*a26);
  if (res[1]!=0) res[1][38]=a26;
  a25=(a25-a24);
  a25=(a7*a25);
  a25=(a21*a25);
  a24=(a17*a11);
  a24=(a24/a23);
  a24=(a12*a24);
  a24=(a4*a24);
  a11=(a5*a11);
  a24=(a24+a11);
  a25=(a25-a24);
  a25=(a19*a25);
  if (res[1]!=0) res[1][39]=a25;
  if (res[1]!=0) res[1][40]=a18;
  if (res[1]!=0) res[1][41]=a18;
  a25=arg[1]? arg[1][45] : 0;
  a24=(a2*a25);
  a11=arg[1]? arg[1][44] : 0;
  a14=(a14*a11);
  a14=(a0*a14);
  a24=(a24-a14);
  if (res[1]!=0) res[1][42]=a24;
  a24=(a3*a25);
  a16=(a16*a11);
  a16=(a0*a16);
  a24=(a24+a16);
  if (res[1]!=0) res[1][43]=a24;
  a24=arg[1]? arg[1][46] : 0;
  if (res[1]!=0) res[1][44]=a24;
  a16=arg[1]? arg[1][47] : 0;
  a11=arg[1]? arg[1][48] : 0;
  a14=(a16+a11);
  a20=(a20*a25);
  a20=(a20/a22);
  a20=(a9*a20);
  a20=(a0*a20);
  a25=(a8*a25);
  a20=(a20+a25);
  a14=(a14-a20);
  a14=(a15*a14);
  if (res[1]!=0) res[1][45]=a14;
  a11=(a11-a16);
  a11=(a7*a11);
  a11=(a21*a11);
  a17=(a17*a24);
  a17=(a17/a23);
  a17=(a12*a17);
  a17=(a4*a17);
  a24=(a5*a24);
  a17=(a17+a24);
  a11=(a11-a17);
  a11=(a19*a11);
  if (res[1]!=0) res[1][46]=a11;
  if (res[1]!=0) res[1][47]=a18;
  if (res[1]!=0) res[1][48]=a18;
  a11=arg[2]? arg[2][3] : 0;
  a17=(a2*a11);
  a24=sin(a1);
  a23=arg[2]? arg[2][2] : 0;
  a16=(a24*a23);
  a16=(a0*a16);
  a17=(a17-a16);
  if (res[2]!=0) res[2][0]=a17;
  a17=(a3*a11);
  a1=cos(a1);
  a23=(a1*a23);
  a23=(a0*a23);
  a17=(a17+a23);
  if (res[2]!=0) res[2][1]=a17;
  a17=arg[2]? arg[2][4] : 0;
  if (res[2]!=0) res[2][2]=a17;
  a23=arg[2]? arg[2][5] : 0;
  a16=arg[2]? arg[2][6] : 0;
  a14=(a23+a16);
  a20=(a0+a0);
  a25=(a20*a11);
  a10=(a10+a10);
  a25=(a25/a10);
  a25=(a9*a25);
  a25=(a0*a25);
  a11=(a8*a11);
  a25=(a25+a11);
  a14=(a14-a25);
  a14=(a15*a14);
  if (res[2]!=0) res[2][3]=a14;
  a16=(a16-a23);
  a16=(a7*a16);
  a16=(a21*a16);
  a23=(a4+a4);
  a14=(a23*a17);
  a13=(a13+a13);
  a14=(a14/a13);
  a14=(a12*a14);
  a14=(a4*a14);
  a17=(a5*a17);
  a14=(a14+a17);
  a16=(a16-a14);
  a16=(a19*a16);
  if (res[2]!=0) res[2][4]=a16;
  a16=1.;
  if (res[2]!=0) res[2][5]=a16;
  if (res[2]!=0) res[2][6]=a18;
  a14=arg[2]? arg[2][10] : 0;
  a2=(a2*a14);
  a17=arg[2]? arg[2][9] : 0;
  a24=(a24*a17);
  a24=(a0*a24);
  a2=(a2-a24);
  if (res[2]!=0) res[2][7]=a2;
  a3=(a3*a14);
  a1=(a1*a17);
  a1=(a0*a1);
  a3=(a3+a1);
  if (res[2]!=0) res[2][8]=a3;
  a3=arg[2]? arg[2][11] : 0;
  if (res[2]!=0) res[2][9]=a3;
  a1=arg[2]? arg[2][12] : 0;
  a17=arg[2]? arg[2][13] : 0;
  a2=(a1+a17);
  a20=(a20*a14);
  a20=(a20/a10);
  a9=(a9*a20);
  a0=(a0*a9);
  a8=(a8*a14);
  a0=(a0+a8);
  a2=(a2-a0);
  a15=(a15*a2);
  if (res[2]!=0) res[2][10]=a15;
  a17=(a17-a1);
  a7=(a7*a17);
  a21=(a21*a7);
  a23=(a23*a3);
  a23=(a23/a13);
  a12=(a12*a23);
  a4=(a4*a12);
  a5=(a5*a3);
  a4=(a4+a5);
  a21=(a21-a4);
  a19=(a19*a21);
  if (res[2]!=0) res[2][11]=a19;
  if (res[2]!=0) res[2][12]=a18;
  if (res[2]!=0) res[2][13]=a16;
  return 0;
}

CASADI_SYMBOL_EXPORT int heron_expl_vde_forw(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int heron_expl_vde_forw_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int heron_expl_vde_forw_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void heron_expl_vde_forw_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int heron_expl_vde_forw_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void heron_expl_vde_forw_release(int mem) {
}

CASADI_SYMBOL_EXPORT void heron_expl_vde_forw_incref(void) {
}

CASADI_SYMBOL_EXPORT void heron_expl_vde_forw_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int heron_expl_vde_forw_n_in(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_int heron_expl_vde_forw_n_out(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_real heron_expl_vde_forw_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* heron_expl_vde_forw_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* heron_expl_vde_forw_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* heron_expl_vde_forw_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    case 3: return casadi_s3;
    case 4: return casadi_s4;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* heron_expl_vde_forw_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int heron_expl_vde_forw_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5;
  if (sz_res) *sz_res = 3;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
